### ISSUE TITLE
Benchmark against MPB

### ISSUE THREAD

**Issue by joaquimg** [JuliaOpt/MathOptInterface.jl#100]
With (#70) [CPLEX](https://github.com/JuliaOpt/MathOptInterface.jl/issues/70#issuecomment-319252597) and [Xpress ](https://github.com/JuliaOpt/MathOptInterface.jl/issues/70#issuecomment-318229543) working for LP we could start preparing benchmark (against MPB).

Should they be in tests or we need a `bench` folder?

Suggestions?

**Comment by mlubin** [comment]
Maybe a separate MathOptInterfaceBenchmarks package?

**Comment by joaquimg** [comment]
Good idea. Should it be a module or just 2 set of scripts?
We might need one folder for MOI and one for MPB since the other packages will be incompatible.

**Comment by mlubin** [comment]
Separate scripts should be fine to start out with

**Comment by mlubin** [comment]
Created https://github.com/JuliaOpt/MathOptInterfaceBenchmarks with appropriate permissions. Benchmarking discussion can continue there.
