### ISSUE TITLE
Documentation not properly showing latex

### ISSUE THREAD

**Issue by guilhermebodin** [JuliaOpt/MathOptInterface.jl#1009]
I think it has some problem in the documentation, that I can't see the latex compiled.
![image](https://user-images.githubusercontent.com/32756941/73008406-42792300-3ded-11ea-9e3f-79dda3707caa.png)

**Comment by mlubin** [comment]
This was fixed in https://github.com/JuliaOpt/MathOptInterface.jl/pull/991. It will appears in the sable docs after the next release.
