### ISSUE TITLE
Add option to make `MOIU.@model` and AbstractOptimizer

### ISSUE THREAD

**Issue by odow** [JuliaOpt/MathOptInterface.jl#1030]
Currently, `@model` makes an `AbstractModel` subtype
https://github.com/JuliaOpt/MathOptInterface.jl/blob/fb303dceaa85dfff8f97e7fe13542c70fdef7754/src/Utilities/model.jl#L927
where `AbstractModel` is
https://github.com/JuliaOpt/MathOptInterface.jl/blob/fb303dceaa85dfff8f97e7fe13542c70fdef7754/src/Utilities/model.jl#L85

However, solvers like [PATH.jl](https://github.com/odow/PATH.jl/issues/4) and [AmplNLWriter](https://github.com/JuliaOpt/AmplNLWriter.jl/issues/97) use `@model` as an `AbstractOptimizer`. We should add a flag to let the super type be chosen by the constructor.

Alternatively, is there any reason not to make `AbstractMode{T} <: MOI.AbstractOptimizer`?

Re-reading, https://github.com/JuliaOpt/MathOptInterface.jl/issues/203, it's not obvious why we have the `ModelLike`/`AbstractOptimizer` distinction.

This feels like it's a legacy of the MPB solver/instance distinction.

cc @chkwon

**Comment by blegat** [comment]
I have no objection for adding an option `@model`, it can even be part of a non-breaking release if we add a default value.
Removing `ModelLike` would be a separate discussion since it is a breaking change. Not sure what to think about this one.

**Comment by odow** [comment]
Closed by #1031
