### ISSUE TITLE
A problem how to query solver state

### ISSUE THREAD

**Issue by YP-Ye** [JuliaOpt/MathOptInterface.jl#1040]
In MathProgBase, we have the following methods in solver callback to query solver state. Are there similar methods in MathOptInterface?
```
cbgetobj(cb)
cbgetbestbound(cb)
cbgetexplorednodes(cb)
cbgetstate(cb)
```

**Comment by odow** [comment]
No. You can only query `callback_value` inside solver-independent callbacks. See https://www.juliaopt.org/JuMP.jl/stable/callbacks/#Information-that-can-be-queried-during-callbacks-1.

**Comment by YP-Ye** [comment]
> No. You can only query `callback_value` inside solver-independent callbacks. See https://www.juliaopt.org/JuMP.jl/stable/callbacks/#Information-that-can-be-queried-during-callbacks-1.

Thanks. I think these methods should be explicitly provided by solvers.jl or MathOptInterface. Are there methods (e.g., cbgetbestbound(cb)) in CPLEX.jl or Gurobi.jl? It will be helpful to control the callback process.

**Comment by odow** [comment]
CPLEX.jl and Gurobi.jl both provide access for solver-dependent callbacks, but this will involve you reading their source code; it isn't documented well.

Closing since this won't be implemented in MOI.
