### ISSUE TITLE
How to construct a nonlinear model and call solver?

### ISSUE THREAD

**Issue by zxjroger** [JuliaOpt/MathOptInterface.jl#1053]
Hi, I have a quick question. In MathProgBae, I write
`model = MathProgBase.NonlinearModel(IpoptSolver())`
to initialize a nonlinear model. What is the corresponding code in MathOptInterface?

Also, is it possible to interrupt the optimization process and query for the solution etc.? Thank you.

**Comment by odow** [comment]
Let's keep this on discourse: https://discourse.julialang.org/t/how-to-call-nonlinear-solver-in-mathoptinterface/36001

**Comment by blegat** [comment]
@zxjroger you can mark @odow's post on Discourse as solving your question if that's the case.
Closing as it seems to be resolved on Discourse
