### ISSUE TITLE
VariablePrimalStart receives a number or a BasisStatusCode or both?

### ISSUE THREAD

**Issue by joaquimg** [JuliaOpt/MathOptInterface.jl#118]
Currently, in **intlinear.jl** it receives a number.

**Comment by joaquimg** [comment]
One possibility is to `setattribute` `VariableBasisStatus()`

**Comment by blegat** [comment]
`VariablePrimalStart` is the value of `VariablePrimal` the variable starts with. For consistency, to set the starting valeu of `VariableBasisStatus`, we should create `VariableBasisStatusStart`.

**Comment by blegat** [comment]
Closing as `VariableBasisStatus` was removed in https://github.com/JuliaOpt/MathOptInterface.jl/pull/679
