### ISSUE TITLE
Parameterize the solver and instance types with a number type

### ISSUE THREAD

**Issue by daviddelaat** [JuliaOpt/MathOptInterface.jl#133]
Should we parameterize the solver and interface types with number types? For instance replace `CSDPSolver` by `CSDPSolver{Float64}` and `CSDPSolverInstance` by `CSDPSolverInstance{Float64}`. 

I think this is necessary, for instance, to make SemidefiniteOptInterface work with high precision solvers.

**Comment by blegat** [comment]
Good point, I think indeed that `SOItoMOIBridge` in SemidefiniteOptInterface will need to be parametrized to allow high precision solvers to be used with it. If a solver supports several precision then it will also need to be parametrized so that the creation of SOItoMOIBridge from a solver is type stable.
Since CSDP only supports Float64 input, I don't see the reason to parametrize it though.

**Comment by mlubin** [comment]
MOI is already pretty type agnostic. [Functions](http://www.juliaopt.org/MathOptInterface.jl/latest/apimanual.html#Functions-1) are parameterized by coefficient type. Solvers and instances can choose to accept or reject constraints with ``ScalarAffineFunction{BigFloat}``, for example. Whether the types of the solvers and instances are themselves parameterized is an implementation question.

Are you suggesting a specific change in MOI or is this meant to be a more general discussion?

**Comment by daviddelaat** [comment]
Yes, I've seen that the functions are parameterized by coefficient types. What I'm wondering is whether the solver and instance types should also be parameterized by a coefficient type. (If yes, then that should probably be in the documentation of this package, which is why I posted the issue here.)

I agree it's a bit weird to parameterize CSDPSolver by Float64 since that's the only possibility. On the other hand it could be useful in some situations to find the precision in a standard location. For instance, it would be kinda nice to be able to write something like
```julia
function LovaszTheta(graph::Graph, solver::AbstractSolver{T}) where T<:Real
# Generate LovaszTheta SDP using precision T
# Solve with the suplied solver
# Return upper bound on the independence number
end
```

**Comment by mlubin** [comment]
The concept of a global coefficient type doesn't currently exist in MOI, and I'm not convinced that we should add one. In principle a solver could support adding constraints with mixed coefficient types. To check if a solver `s` is capable of solving an LP problem with `BigFloat` coefficients, you can use:
```julia
supportsproblem(s, ScalarAffineFunction{BigFloat},
    [(ScalarAffineFunction{BigFloat},Zeros),
    (ScalarAffineFunction{BigFloat},LessThan),
    (ScalarAffineFunction{BigFloat},GreaterThan)])
```
Yes, unfortunately this doesn't interact with type dispatch because it's more like a complex trait.

**Comment by blegat** [comment]
I would be in favor of having a trait or a function for querying the preferred coefficient type of the solver.
For cddlib, it both supports `Rational{BigInt}` and `Float64` so I am planning to parametrize the `CDDSolver`

**Comment by daviddelaat** [comment]
Yes, I think a function for querying the coefficient type is also a good possibility. 

Then we get
```julia
mutable struct SOItoMOIBridge{T <: Number, ST <: AbstractSDSolver, SIT <: AbstractSDSolverInstance} <: MOI.AbstractSolverInstance
```
instead of
```julia
mutable struct SOItoMOIBridge{T <: Number, ST <: AbstractSDSolver{T}, SIT <: AbstractSDSolverInstance{T}} <: MOI.AbstractSolverInstance{T}
```

And we get something like
```julia
function lovasztheta(graph::Graph, solver::AbstractSolver)
    T = coefficienttype(solver)
```
instead of
```julia
function lovasztheta(graph::Graph, solver::AbstractSolver{T}) where T<:Real
```

It's difficult for me to assert the performance implications of this but this is definitely an option.

**Comment by mlubin** [comment]
Options for a coefficient type attribute were discussed in https://github.com/JuliaOpt/MathOptInterface.jl/pull/148. We won't be parameterizing the `AbstractInstance` type.
