### ISSUE TITLE
Naming of set fields

### ISSUE THREAD

**Issue by odow** [JuliaOpt/MathOptInterface.jl#137]
There are a few inconsistencies in the naming of various fields within sets

- [ ]  `dim` instead of `dimension`: most of the time, long names are preferred (i.e. [`lower`](https://github.com/JuliaOpt/MathOptInterface.jl/blob/master/src/sets.jl#L74)). However, `dim` is used in place of `dimension.
- [ ] `a` is not descriptive in the [`PowerCone`](https://github.com/JuliaOpt/MathOptInterface.jl/blob/master/src/sets.jl#L146): should it be `exponent` or something similar?
- [ ] `l` and `u` in [`Semicontinuous`](https://github.com/JuliaOpt/MathOptInterface.jl/blob/master/src/sets.jl#L228-L229) instead of `lower` and `upper`

Are we happy with these or do we want to change?

**Comment by joaquimg** [comment]
+1 for change
