### ISSUE TITLE
Solver-dependent options

### ISSUE THREAD

**Issue by joaquimg** [JuliaOpt/MathOptInterface.jl#139]
Should we have a way to deal with solver specific attributes?
like:
`setattribute!(m::AbstractInstance, ::SolverSpecificAttribute, parameter::Any, value::Any)`

So that the parameter could be a String, Symbol, Integer, whatever the solver interface understands.

would be some kind of MOI shortcut for the `setparam!` and friends...

This way even jump would have a "standard" way to have the user passing parameters (outside `Model(param = val)`). So that the user does not have to use `solverX.setparam!(jump.moi.inner, param, val)`

**Comment by mlubin** [comment]
My idea was that solvers could just define, e.g.,
```julia
struct CPLEXFancyAttribute <: MOI.AbstractSolverAttribute
...
end
```
and JuMP would pass that though as any other MOI attribute (this is still missing from JuMP). Do we need to modify the type hierarchy?

**Comment by joaquimg** [comment]
That is ok, and maybe the best way is do it via metaprograming, since we have so many attributes. 
All the functions would be just a setparam with a different parameter value.

```julia
param = Dict{DataType,Int32}( :XpressMIPGAP => 32)

#generatevia metaprog:
struct XpressMIPGAP <: MOI.AbstractSolverAttribute
end
function setattribute!(m::XpressSolver, ::XpressMIPGAP, value)
    setparam!(m, 45, value)
end
function getattribute(m::XpressSolver, ::XpressMIPGAP)
    getparam(m, 45)
end
```

A second option would be a generic type that would contain the integer (refering to the parameter) inside it. An we have functions to set the integer.

```julia
struct  XpressSolverAttribute <: MOI.AbstractSolverAttribute
    val::Int32
end
XpressMIPGAP() = XpressSolverAttribute(45)
```
instead of
```julia
const MIPGAP = 45
```

**Comment by mlubin** [comment]
The second option seems pretty reasonable, but up to the interface authors.
