### ISSUE TITLE
default value for Sense?

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/MathOptInterface.jl#14]
Currently we haven't defined what happens when the `Sense` attribute is never set. Should we define it to be minimization by default or make it required to provide a sense? I'm leaning towards the latter.

**Comment by joaquimg** [comment]
+1 minimization by default

**Comment by mlubin** [comment]
The interface is already very clear and explicit about all other aspects of the problem, so it seems more consistent to make setting the sense obligatory. Open for discussion though.

**Comment by chriscoey** [comment]
So the standard form problem is [defined with minimization](https://github.com/JuliaOpt/MathOptInterface.jl/pull/13/files#diff-d8be55aa74364fe9aa7535b696fe9920R29) currently, but given that it can be Min or Max, maybe that standard form should say "Min/Max" (with a bullet point to explain). In that case certainly it makes sense not to set a default. This is MOI (not JuMP) so it can and should be verbose, IMO.

**Comment by joaquimg** [comment]
The `standard form problem` in the manual is minimization and not just a place holder (which is good because it would be confusing)

**Comment by chriscoey** [comment]
jinx

**Comment by joaquimg** [comment]
hehe

**Comment by joaquimg** [comment]
I am fine with verbose, but solvers have defaults... Which is better to reduce errors/problems in the APIs?
Other than that, I see no big advantages in each way

**Comment by chriscoey** [comment]
If we leave the standard form problem with Min definition, then I'm fine with Min as default. If we change it to Min/Max, then I'd say no default.

**Comment by ccoffrin** [comment]
In the other APIs I have used the sense has most often been explicit.  For example, in AMPL you have to say `maximize f(x)` in gurobi's API you say `setObjective(obj, GRB.MINIMIZE)`, in CP tools such as MiniZinc you say `solve minimize f(x);`

In general I prefer being explicit rather than implicit; so if you have to say "the objective is f(x)" then I would prefer to be explicit and require the sense and not have a default.

**Comment by joaquimg** [comment]
Should we set sense in the setobjective function? (and have a method to change it)

**Comment by joehuchette** [comment]
Thoughts on having a ``Feasibility`` sense that is also the default?

**Comment by mlubin** [comment]
Making the sense a required argument to ``setobjective!`` seems reasonable to me.

@joehuchette, in which cases is it useful to have an explicit ``Feasibility`` sense instead of having an empty objective function?

**Comment by joehuchette** [comment]
Because there are many problems that are naturally feasibility problems, and it's more natural to say that a feasibility problem corresponds to the ``:Feasibility`` sense, rather than the ``:Minimization`` sense with an objective function equal to zero?

**Comment by ccoffrin** [comment]
I am in favor of `:Feasibility` by default and then having an explicit Min/Max value in set objective.  That is consistent with my experince using other tools.

**Comment by blegat** [comment]
Also in favor of having mandatory Min/Max in `setobjective!` and having `:Feasibility` by default. It should also possible to set `:Feasibility` back. One usage example, see https://github.com/JuliaOpt/Gurobi.jl/issues/80
* You solve the problem, it finds an unbounded ray but you don't know if the feasible set is non-empty
* You set the objective to `:Feasibility` and resolve to get a feasible solution.
