### ISSUE TITLE
writeinstance method?

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/MathOptInterface.jl#149]
We currently don't have any methods to request that an instance be written to a file.

**Comment by odow** [comment]
Yes we do https://github.com/JuliaOpt/MathOptInterface.jl/blob/master/src/MathOptInterface.jl#L70

**Comment by mlubin** [comment]
Missing from the docs then?

**Comment by mlubin** [comment]
Also should be renamed to writeinstance. writeproblem doesn't make sense in the current MOI conventions

**Comment by odow** [comment]
Ok I'll fix
