### ISSUE TITLE
lookup by name

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/MathOptInterface.jl#151]
Now that we have variable and constraint names, it makes sense to be able to look up the references by names. This seems especially relevant when transferring an instance across files/solvers. Strings are a reasonable key to match up the pieces of the model; they're generally simpler to handle than e.g., what [JuMP does](https://github.com/JuliaOpt/JuMP.jl/blob/9466fe9bc15caae3684f980b34d52a545a6c1d12/src/solverinterface.jl#L21) to map references between the solver instance and the standalone instance.

To start the discussion I would propose:
```julia
MOI.has(m::AbstractInstance, VariableReference, "foo") # returns true or false
MOI.lookup(m::AbstractInstance, VariableReference, "foo") # returns a VariableReference if it exists, `KeyError` otherwise

MOI.has(m::AbstractInstance, ConstraintReference{F,S}, "foo") # returns true or false
MOI.lookup(m::AbstractInstance, ConstraintReference{F,S}, "foo") # returns a ConstraintReference{F,S} if it exists, `KeyError` otherwise

# lazy, type unstable interface
MOI.has(m::AbstractInstance, ConstraintReference, "foo") # returns true or false
MOI.lookup(m::AbstractInstance, ConstraintReference, "foo") # returns a ConstraintReference{F,S} if it exists for some (F,S), `KeyError` otherwise
```

I would say that every reference needs to have either a unique name or an empty string for a name. Immediate error when creating a duplicate name.

**Comment by odow** [comment]
To minimize the number of different MOI functions I propose
```julia
MOI.isvalid(m, VariableReference,  "foo")
MOI.isvalid(m, ConstraintReference{F,S}, "foo")
MOI.isvalid(m, ConstraintReference, "foo")
# or
MOI.cangetattribute(m, VariableReference,  "foo")
MOI.cangetattribute(m, ConstraintReference{F,S}, "foo")
MOI.cangetattribute(m, ConstraintReference, "foo")
```
instead of `MOI.has` and
```julia
MOI.getattribute(m, VariableReference,  "foo")
MOI.getattribute(m, ConstraintReference{F,S},  "foo")
MOI.getattribute(m, ConstraintReference,  "foo")
```
 instead of `MOI.lookup`.

> I would say that every reference needs to have either a unique name or an empty string for a name. Immediate error when creating a duplicate name.

+100

**Comment by mlubin** [comment]
The use of `MOI.isvalid` works for me, but `cangetattribute` seems like a bit too much of a pun because `VariableReference` and `ConstraintReference` are not attributes of the instance.

**Comment by mlubin** [comment]
Unless we want to rename `getattribute` and `setattribute!` to `MOI.get` and `MOI.set!`.

**Comment by odow** [comment]
I am a fan of this. `MOI.get(m, MOI.NumberOfVariables())` is very clean.

**Comment by blegat** [comment]
I like the idea. `MOI.getattribute(..., ::AbstractAttribute)` was redundant since there is attribute both in the type and function name.
We should consider whether we want to use `Base.get`.
In that case, the third attribute should be a default value to be used in case the attribute cannot be got.

**Comment by mlubin** [comment]
I don't think we should use `Base.get` because there's no `Base.set!`, `Base.canget`, `Base.canset` etc, and the signature of `Base.get` doesn't really match what we want anyway.
