### ISSUE TITLE
some exception handling

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/MathOptInterface.jl#16]
Define what should happen when you ask a solver to do something that it can't do. Most of this is covered by ``cansetattribute``, ``cangetattribute``, and ``supportsproblem``, but not everything (like adding a certain constraint after solving: https://github.com/JuliaOpt/MathOptInterface.jl/issues/8). We have the ``InvalidInstance`` termination status code, although you would normally test that only after calling ``optimize!``.

We should probably define a standard exception that solvers should throw which can be intercepted by JuMP to infer that a solver won't allow a certain action. For other exceptions JuMP might decide to let them pass through to the user.

**Comment by blegat** [comment]
Shouldn't all solver support adding constraint after solving ? If it is not supported then in the wrapper we just create a new one when `optimize!` is called.

**Comment by mlubin** [comment]
The most straightforward implementation of that would be for each solver wrapper to store an extra copy of the problem data. We want to avoid having 3 copies of the problem data (in the solver API, solver wrapper, and JuMP). It's also redundant if you're using JuMP because JuMP can always regenerate the model.

**Comment by blegat** [comment]
It makes sense indeed, thanks for the explanation.

**Comment by blegat** [comment]
@mlubin Hasn't this been resolved by https://github.com/JuliaOpt/MathOptInterface.jl/pull/436 ?

**Comment by mlubin** [comment]
Yep!
