### ISSUE TITLE
add conic tests with non-consecutive cone indices

### ISSUE THREAD

**Issue by chriscoey** [JuliaOpt/MathOptInterface.jl#167]
A major bug in Mosek.jl was only just discovered (https://github.com/JuliaOpt/Mosek.jl/issues/130). 

There need to be tests to make sure solvers don't assume consecutive conic indices.

**Comment by chriscoey** [comment]
I added tests to MPB in https://github.com/JuliaOpt/MathProgBase.jl/pull/204

**Comment by mlubin** [comment]
Ported to MOIT
