### ISSUE TITLE
MOI release?

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/MathOptInterface.jl#174]
I don't expect any more large breaking changes to MOI soon. What do we think about tagging 0.1.0 in METADATA?

**Comment by joaquimg** [comment]
We have not experimented with solver specific attributes, but that should not be breaking...
Should we tag some of the solver interfaces so that people can start playing with it?
And maybe tag the tests for the ones that want to start implementing interfaces.

**Comment by mlubin** [comment]
Have we concluded that the MOI interfaces will be in separate packages? Are the MPB interfaces going to disappear?

**Comment by joaquimg** [comment]
I vote for separate packages. If it was not breaking I would like to move MPB out of the low level interfaces. I like the way GLPK is.

**Comment by blegat** [comment]
Could we just wait before merging logdet, detrootn and PSDsquare sets ? (PR comming soon)

**Comment by joaquimg** [comment]
It would be great to have those!

**Comment by mlubin** [comment]
We should also release as 0.7 only, to follow up with our previous plans. Maybe we should wait for 0.7-alpha to be tagged first.

**Comment by blegat** [comment]
There is no issue of MOI being released for 0.6, the issue was more with existing JuliaOpt ecosystem.
But if a solver does
1) Release MOISolver.jl under 0.6, leave MPB code inside Solver.jl
2) When Julia v0.7 is released, drop support for Julia v0.6 in Solver.jl and remove MPB code (or move it to MPBSolver.jl)

then it will work with MOI.

**Comment by mlubin** [comment]
Let's discuss the transition plan during the call next week.

**Comment by mlubin** [comment]
I think tossing the MPB code in the transition to 0.7 will be a bit rough on users. Some people might want to continue using JuMP 0.18 on Julia 0.7, and that's okay. I don't want to promise that JuMP 0.19 will be available at the same time as the Julia 0.7 release either, we still need to have a substantial testing period once the coding is done.

I'd suggest releasing Solver.jl packages with a minimum version of `0.7-alpha` (when it's released) and at that time moving the corresponding MPB code into a new MPBSolver.jl package. This way the upgrade path to use MPB under 0.7 is just to switch packages. We should still be careful not to make these changes visible on 0.6.

@ccoffrin

**Comment by joaquimg** [comment]
bump, whats the plan here?

**Comment by mlubin** [comment]
Given that MOIT was just merged in, I'm expecting all or some of MOIU to follow. After that I'd say we're in a pretty good position to make an initial release.

**Comment by tkoolen** [comment]
Ready for an initial release now? Would be great if I could get the OSQP MOI PR merged soon.

**Comment by mlubin** [comment]
@tkoolen are you planning on putting an upper bound on the MOI required version in OSQP? Because we have multiple breaking changes queued up to be implemented (#211, #243).

**Comment by tkoolen** [comment]
Sure, that's fine.

**Comment by mlubin** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/13563

**Comment by mlubin** [comment]
Done!
