### ISSUE TITLE
Scaled symmetric matrices

### ISSUE THREAD

**Issue by blegat** [JuliaOpt/MathOptInterface.jl#176]
As explained [here](https://github.com/cvxgrp/scs), scaled symmetric matrix format has the advantage that the scalar product of the vector correspond to the scalar product of the matrices. However in modelling, we always prefer to talk about the upper triangular part of the matrix without scaling (otherwise there is complicates cases to check with the dual and so on).
As we are created more cones storing a matrix, for consistency we need to create one for scaled symmetric matrix format each time.
Is it worth keeping this PositiveSemidefiniteConeScaled or should we get rid of it ?

* Keep it :+1: 
* Get rid of it :-1: 

cc @ulfworsoe

**Comment by ulfworsoe** [comment]
In my (quite personal) opinion it is not necessary in an interface at the MathOptInterface level. It is simpler without it, and it can be left to a modeling level above to unfold the dot-product correctly.

**Comment by mlubin** [comment]
We should get rid of it, but we need a clear discussion in the documentation about how to handle duality. The MOI dual as written is incorrect for the triangle matrices.
@chriscoey
