### ISSUE TITLE
Column generation interface

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/MathOptInterface.jl#18]
We're missing this interface, and it needs some thought to fit in with the current design.

**Comment by mlubin** [comment]
One option is to not have a special column generation interface. We just add variables and submit constraint modifications and let the wrapper deal with calling the right API.

**Comment by chriscoey** [comment]
I agree with that - try to keep MOI as simple as possible. If absolutely needed later, it can be added.

**Comment by joaquimg** [comment]
All the solvers support modifying constraints?
Once you mentioned Clp might not: JuliaOpt/MathProgBase.jl#139
Does it accept column generation?

**Comment by mlubin** [comment]
Clp supports column generation and not modifying constraints, IIRC. The solver wrapper can be responsible for collecting the modifications correctly and calling the column generation API.

**Comment by mlubin** [comment]
In https://github.com/JuliaOpt/MathOptInterface.jl/commit/3dc93d5c0caeb613309ec0f20baa5c746fb518f6 I added the function modifications to cover the column generation case. We should have some discussion of this in the manual.
