### ISSUE TITLE
cancopy

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/MathOptInterface.jl#182]
https://github.com/JuliaOpt/MathOptInterface.jl/pull/181#issuecomment-348825315

**Comment by blegat** [comment]
That's a good idea. When SCS says that it does not support a constraint with `cancopy`, or Mosek says that it does not support a constraint with `canaddconstraint`, JuMP could then automatically add a bridge to try to fix the situation. What do you think ?

**Comment by mlubin** [comment]
I'm not convinced about the automatic bridging, but we can experiment with it.

**Comment by blegat** [comment]
I am also still undecided, just throwing ideas :-P
