### ISSUE TITLE
how does read! work?

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/MathOptInterface.jl#185]
How does the user get the indices of the variables and constraints loaded using `read!`?

**Comment by odow** [comment]
`ListOfVariableReferences` or get by name.

**Comment by mlubin** [comment]
`ListOfVariableReferences` could return them in any order, though.
Could we add a note to the `read!` docs about looking up by name? I had already forgotten this.

**Comment by odow** [comment]
It's not always obvious what order should be returned. Especially in the case of an LP file for example where column order isn't strictly defined.
