### ISSUE TITLE
== and hash for ConstraintIndex and VariableIndex

### ISSUE THREAD

**Issue by blegat** [JuliaOpt/MathOptInterface.jl#186]
What do you think of defining `==` and `Base.hash` on `VariableIndex` and `ConstraintIndex` using the `value` field ? For instance,
```julia
Base.==(vi1::VariableIndex, vi2::VariableIndex) = vi1.value == vi2.value
Base.hash(vi::VariableIndex, u) = hash(vi.value, u)
Base.==(ci1::ConstraintIndex{F, S}, ci2::ConstraintIndex{F, S}) where {F, S} = ci1.value == ci2.value
Base.==(ci1::ConstraintIndex, ci2::ConstraintIndex) = false
Base.hash(ci::ConstraintIndex{F, S}, u) where {F, S} = hash(S, hash(F, hash(ci.value, u)))
```
Julia conventions require that instances that are `==` should have the same hash. If we want to define an `MOI.duplicate` function returning an instance with the same indices, we will need equality to be with the value and not be equivalent to `===`.

**Comment by mlubin** [comment]
Isn't this the default behavior for isbits structs anyway?

**Comment by blegat** [comment]
I didn't know it was the default for isbits type. If it is already what's is done then it's fine we don't have to do anything :)

**Comment by mlubin** [comment]
Any two `VariableIndex` objects with matching `value` will have the same hash and will compare as equal.

**Comment by blegat** [comment]
I just checked, we even have `VariableIndex(1) === VariableIndex(1)` a they have the same `object_id`. The hash is done with the object_id by default so they also have the same hash.
However, I have noticed that object_id is a lot slower than just taking `.value` so redefining `hash` for VariableIndex might improve the performance of all Dictionary using it as index
```julia
julia> @benchmark hash($v)
BenchmarkTools.Trial: 
  memory estimate:  16 bytes
  allocs estimate:  1
  --------------
  minimum time:     24.779 ns (0.00% GC)
  median time:      26.816 ns (0.00% GC)
  mean time:        28.181 ns (1.38% GC)
  maximum time:     847.498 ns (89.66% GC)
  --------------
  samples:          10000
  evals/sample:     994

julia> @benchmark hash($(v.value))
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     3.454 ns (0.00% GC)
  median time:      4.183 ns (0.00% GC)
  mean time:        4.158 ns (0.00% GC)
  maximum time:     23.625 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1000

julia> Base.hash(v::MOI.VariableIndex, u::UInt64) = hash(v.value, u)

julia> @benchmark hash($v)
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     3.465 ns (0.00% GC)
  median time:      4.213 ns (0.00% GC)
  mean time:        4.210 ns (0.00% GC)
  maximum time:     22.289 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1000

julia> @benchmark object_id($v)
BenchmarkTools.Trial: 
  memory estimate:  16 bytes
  allocs estimate:  1
  --------------
  minimum time:     22.721 ns (0.00% GC)
  median time:      23.124 ns (0.00% GC)
  mean time:        25.038 ns (1.59% GC)
  maximum time:     720.743 ns (90.99% GC)

```

**Comment by mlubin** [comment]
The upstream issue is https://github.com/JuliaLang/julia/issues/10208. Let's not mess with hashing until we need to.
