### ISSUE TITLE
Interpreting the output of cancopy

### ISSUE THREAD

**Issue by blegat** [JuliaOpt/MathOptInterface.jl#188]
As mentionned in this PR https://github.com/JuliaOpt/MathOptInterfaceUtilities.jl/pull/50 (it would also be useful for an automatic bridger (described here: https://github.com/JuliaOpt/JuMP.jl/issues/1152#issuecomment-354373234)), it would be nice to have a way to detect why `cancopy` return `false`.

For instance we could have
```julia
cancopyconstraint(instance::AbstractInstance, f::AbstractFunction, s::AbstractSet)
```
It returns false if `cancopy(instance, src)` returns false for any possible instance `src` that contains the constraint `f`-in-`s`.
That is, if the constraint is supported but cannot be mixed with specific other constraints, then it should return true.

This is useful for automatic bridger as it shouls that this constraint definitely need to be bridged.

What do you think ?

**Comment by mlubin** [comment]
`cancopyconstraint` doesn't address the main issue. `cancopy` could return `false` for lots of reasons like:
- not supporting the combination of quadratic and SOC constraints
- invalid coefficients
- unsupported attributes

In the short term I think a reasonable solution is to support returning errors with human-readable strings explaining what went wrong (https://github.com/JuliaOpt/MathOptInterface.jl/issues/16). Providing the infrastructure for automatic bridges is not a high priority for me; it's not blocking for JuMP 0.19, while error messages are.

Maybe `cancopy` is not the right approach because it forces an extra pass through the problem and doesn't return very useful information back. It would be more useful to have a programmatic way to report that `copy!` failed.

**Comment by blegat** [comment]
Yes, `cancopy` isn't very helpful here. Maybe `copy!` could return a tuple instead of just the dictionary-like object. The first element is the dictionary-like object and the second is a boolean : `true` means that everything went well and `false` means that the `copy!` was not done.
Then one could do `MOI.get(instance, MOI.CopyFailureReason())`. The disadvantage of this approach is that the copy failure reason needs to be stored on the instance so it adds more state.
The copy failure reason could also simply be returned as the second element of the tuple.
For the failure reason, an `enum` might not be enough, we might do something like
```julia
abstract type CopyStatus end
Base.show(io::IO, s::CopyStatus) = print(io, reason(s))
struct Success <: CopyStatus end
struct UnsupportedAttribute{AT<:MOI.AbstractInstanceAttribute} end
reason(ua::UnsupportedAttribute{AT}) where AT = "Unsupported Attribute $(AT)"
struct UnsupportedCoefficientType{T} end
reason(ic::InvalidCoefficient{T}) where T = "Invalid coefficient $(T)"
struct UnsupportedConstraintCombination{F1, S1, F2, S2} end
struct UnsupportedConstraint{F, S} end
struct UnsupportedObjective{F} end
struct OtherFailure <: CopyStatus
    reason::String # does not enter in other categories so a string is used
end
reason(f::OtherFailure) = f.reason
```
What do you think ?

**Comment by mlubin** [comment]
How about:
```julia
@enum CopyStatus CopySuccess CopyUnsupportedAttribute CopyUnsupportedConstraint CopyOtherError

struct CopyResult{DictLike}
status::CopyStatus
message::String # Human-friendly explanation why the copy failed
indexmap::DictLike # Only valid if status is CopySuccess
end
```

and `copy!` returns a `CopyResult`.

Co-opting copy failures to make automatic bridging work really complicates the interface and doesn't do the right thing anyway. You only get one piece of information back like `UnsupportedConstraint{F, S}`, but what if the solver doesn't support lots of constraints? Do you have to call `copy!` multiple times to probe the information?

**Comment by blegat** [comment]
What about addressing the two problems (the one for InstanceManager and the one for AutomaticBridger) differently then ?
Your proposal solves the issue for the InstanceManager and for programatic use we can do something like
```julia
supportconstraint(instance::AbstractInstance, ::Type{<:AbstractFunction}, ::Type{<:AbstractSet})
```
which corresponds to the definition of `cancopyconstraint` written in the first post. Here we only make it depend on the type of function/sets to allow the lightweight use of calling it for every element of the `ListOfConstraints` instead of needing to go through each constraint.

**Comment by mlubin** [comment]
Something like that makes sense, what about for attributes? (Including the important objective function attribute.)
