### ISSUE TITLE
Setting attributes for a subset of variables only

### ISSUE THREAD

**Issue by blegat** [JuliaOpt/MathOptInterface.jl#191]
Currently we have
```julia
    canget(instance::AbstractInstance, attr::AbstractVariableAttribute, v::VariableIndex)::Bool
    canget(instance::AbstractInstance, attr::AbstractConstraintAttribute, c::ConstraintIndex{F,S})::Bool

Return a `Bool` indicating whether the instance `instance` currently has a value for the attributed specified by attribute type `attr` applied to the variable indexed by `v` or constraint indexed by `c`.

    canget(instance::AbstractInstance, attr::AbstractVariableAttribute, v::Vector{VariableIndex})::Bool
    canget(instance::AbstractInstance, attr::AbstractConstraintAttribute, c::Vector{ConstraintIndex{F,S}})::Bool

Return a `Bool` indicating whether the instance `instance` currently has a value for the attributed specified by attribute type `attr` applied to *every* variable indexed by `v` or constraint indexed by `c`.
```
This leaves the possibility that for some attributes can be got from some variables but not others. During a copy, it would be inefficient to check for every variable attributes if canget is false or not.
One possible solution would be to have `canget(instance, attr)` without the indices arguments and disallow attributes to be set only for some variables but not all.
One other solution would be to do something like
```julia
# inside copy!(dest, src)
vars = MOI.get(src, MOI.ListOfVariableIndices())
for attr in MOI.get(src, MOI.ListOfVariablesAttributesSet())
    # We know that attr has been set to at least one variable
    if MOI.canget(src, attr, vars)
        ...
    else
        for var in vars
             if MOI.canget(src, attr, var)
                ...
            end
        end
    end
end
```
With this code, `MOI.canget` will be called on every variable **only if** `src` gives a variable attribute, so it means that it has been set for at least one variable, and then return false for `MOI.canget(src, attr, vars)` which means that is has been set for only some variables. So instead of disallowing the case of variable attribute only set for some variables, we just make the inefficiency only happen in this case.

**Comment by mlubin** [comment]
I think it's reasonable to redefine `canget` to:
```julia
canget(instance::AbstractInstance, attr::AbstractVariableAttribute)
```
and
```julia
canget(instance::AbstractInstance, attr::AbstractConstraintAttribute, F::AbstractFunction, S::AbstractSet)
```
Allow some attributes to only be defined for a subset of variables significantly complicates generic code like `copy!`. For constraints, attributes should be defined for all constraints of the same class.

**Comment by blegat** [comment]
Shouldn't be like
```julia
canget(instance::AbstractInstance, attr::AbstractConstraintAttribute, ::Type{F}, ::Type{S})
```
or even
```julia
canget(instance::AbstractInstance, attr::AbstractConstraintAttribute, ::Type{<:ConstraintIndex})
```
?
It should depend on the actual value of the function or set

**Comment by mlubin** [comment]
You're correct, it should depend on the types.
