### ISSUE TITLE
get ObjectiveFunction is not type stable

### ISSUE THREAD

**Issue by joaquimg** [JuliaOpt/MathOptInterface.jl#197]
We can query the function type...

**Comment by mlubin** [comment]
Possible solutions are discussed in https://github.com/JuliaOpt/MathOptInterface.jl/issues/31. In general attributes weren't designed to be type stable.

**Comment by blegat** [comment]
We also have the issue that `canget` and `canset` does not depend on the type of the function.
Maybe we should have
```julia
struct ObjectiveFunction{F<:AbstractFunction} end
```

**Comment by joaquimg** [comment]
I like this solution of having the function type as a parameter in `ObjectiveFunction`

**Comment by mlubin** [comment]
I can support that.

**Comment by blegat** [comment]
That has important implication to #196 , it means that we will rather do
```julia
supportsattribute(instance::AbstractInstance, attr::AbstractInstanceAttribute)
```
instead of
```julia
supportsattribute(instance::AbstractInstance, attr::AbstractInstanceAttribute, ::Type{V}) where V
```
and I think it is for the better.
