### ISSUE TITLE
Fallbacks for vector attributes

### ISSUE THREAD

**Issue by odow** [JuliaOpt/MathOptInterface.jl#212]
As proposed by @tkoolen in #209: MOI.get with vector variable indices: is that really needed? I saw an overload in SCS that just broadcasted to the scalar function, https://github.com/JuliaOpt/MathOptInterfaceSCS.jl/blob/a0f8467245d8b0a1814cf7248b174c1462990ae5/src/attributes.jl#L51. Can’t that be the default fallback?

I forgot whether we had a discussion about default fallbacks...

**Comment by mlubin** [comment]
I don't remember a good reason to not implement the default fallback. Maybe ambiguity issues?

**Comment by blegat** [comment]
I am in favor of a fallback. If we use types that are not too specific like in
```julia
MOI.get(::AbstractInstance, ::AbstractVariableAttribute, ::Vector{VariableIndex})
```
it just forces solvers to do
```julia
MOI.get(::SolverType, ::SomeVarAttribute, ::Any) # Bad
MOI.get(::SolverType, ::SomeVarAttribute, ::VariableIndex) # Good
```
