### ISSUE TITLE
candelete is inconsistent with canget

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/MathOptInterface.jl#218]
We would probably like to pass in the type of the index instead of the index value itself.

**Comment by blegat** [comment]
There might be cases where some variables can be deleted and some cannot. For instance, a solver could say that a variable cannot be deleted if it still appears in some constraints

**Comment by mlubin** [comment]
That sounds like it could also just be an error on `delete!`. Unclear though...

**Comment by blegat** [comment]
There is the same performance issue in `CachingOptimizer` for deleting constraints so I think we should go for it

**Comment by odow** [comment]
Bump. I just encountered this.
