### ISSUE TITLE
Docs: uniqueness of `ConstraintIndex`es in a model

### ISSUE THREAD

**Issue by tkoolen** [JuliaOpt/MathOptInterface.jl#227]
Of course you can't have two `ConstraintIndex`es of the same type *and* with the same `value` in a model, but what if the types are different? I couldn't find that in the docs.

**Comment by mlubin** [comment]
It's valid to have nonunique indices across different constraint types. `MOIU.Model` chose to implement a model-level constraint counter, but other `ModelLike` implementations might choose to use different counters for linear and quadratic constraints, for example. It's worth documenting better.
See https://github.com/JuliaOpt/MathOptInterfaceUtilities.jl/issues/44.
