### ISSUE TITLE
Tests to be ported from MPB

### ISSUE THREAD

**Issue by joaquimg** [JuliaOpt/MathOptInterface.jl#23]
List of tests to be ported from MPB

**linproginterface.jl**
- [x] 1 "Testing LP interface with $solver"
    - [x] a "Basic interface" 
    - [x] b "addvar! interface"  
    - [x] c "setconstrLB! and setconstrUB!"
        now: "Modify constants in Nonnegative and Nonpositive"
        and: "Modify GreaterThan and LessThan sets as linear constraints"
    - [x] d "Issue #40 from Gurobi.jl"
    - [x] e "Change coeffs, del constr, del var"
- [ ] 2 "Testing LP interface extra with $solver"
    - [ ] a "setconstrLB! and setcontrUB!"
    - [ ] b "setvarLB! and setvarUB!"

**linprog.jl**
- [ ] 1 "Testing linprog and subfunctions with $solver"
    - [ ] a "LP1"
    - [ ] b "LP2"
    - [x] c "LP3 infeasible"
    - [x] d "LP4 unbounded"
    - [x] e "LP4 unbounded with unique ray"

**mixintprog.jl**
- [x] 1 "Testing mixintprog with $solver"
    now: "Knapsack Model"

**quadprog.jl**
- [x] 1 "Testing quadprog with $solver"
    - [x] a "QP1"
    - [x] b "QP2"
- [ ] 2 "Testing QP duals with $solver"
    - [ ] a "QP1"
    - [ ] b "QP2"
- [x] 3 "Testing SOCP interface with $solver"

**conicinterface.jl**
- [x] 1 "Testing linear problems through conic interface with $solver"
    - [x] a "LIN1"
    - [x] b "LIN1A"
    - [x] c "LIN2"
    - [x] d "LIN2A"
    - [x] e "LIN3 infeasible"
    - [x] f "LIN4 infeasible"
- [x] 2 "Testing SOC problems through conic interface with $solver"
    - [x] a "SOC1"
    - [x] b "SOC1A"
    - [x] c "SOC2"
    - [x] d "SOC2A"
    - [x] e "SOC3 infeasible"
    - [x] f "SOC4"
- [x] 3 "Testing SOCRotated problems through conic interface with $solver"
    - [x] a "SOCRotated1"
    - [x] b "SOCRotated1A"
    - [x] c "SOCRotated2 infeasible"
- [x] 4 "Testing SOCINT problems through conic interface with $solver"
- [ ] 5 "Testing EXP problems through conic interface with $solver"
    - [ ] a "EXP1"
    - [ ] b "EXP1A"
    - [ ] c "EXP2"
    - [ ] d "EXP3"
- [x] 6 "Testing SDP problems through conic interface with $solver"
    - [x] a "SDP1"
    - [x] a "SDP1"  with `PositiveSemidefinteConeScaled`
    - [x] b "SDP2"

**Comment by mlubin** [comment]
I would remove linprog, quadprog, and mixintprog tests from here, pending discussion at https://github.com/JuliaOpt/MathOptInterface.jl/issues/24.

**Comment by joaquimg** [comment]
I think we could translate them into MOI and add them, after all they were testing some function implicitly.
 - mixintprog is done anyways, 
 - quadprog should have a MOI equivalent, 
 - linprog should have a MOI equivalent if they are different from other tests

**Comment by joaquimg** [comment]
I will start MOI/contquadratic.jl

**Comment by blegat** [comment]
I am doing SDP1 and SDP2

**Comment by joaquimg** [comment]
#38 closed: 
**linproginterface.jl** 
- 1a "Basic interface"
- 1b "addvar! interface"
- 1c "setconstrLB! and setconstrUB!"
- part of 1e "Change coeffs, del constr, del var"

for 1e we still dont´t have:
- delete variable
- copy problem (is that even in MOI already?)

Do you agree @mlubin and @IssamT ? Am I missing something?

**Comment by joaquimg** [comment]
#25 closed almost all the **quadprog**, just need to get duals. 
Waiting for #43.

**Comment by IssamT** [comment]
@joaquimg thanks for the summary.

If i understood well 1b in mathprogbase was adding variables one by one. So I will keep the **1b** even if most of it is redundant with **1a**.

For **1c** It doesn t seem to me that we can modify all lb to constraints with MOI. Not saying that we should. Just saying that this test isn't needed for the current MOI.

yes we need to test delete var. so I ll add **1e**

and I don't know if copying a problem is planned with MOI. is it?

**Comment by IssamT** [comment]
Also addvar! of MathProgBase used to set the obj coeff at the same time. This will be a difference in **1b**

**Comment by joaquimg** [comment]
**linproginterface.jl** 1b closed by #49
**conicinterface.jl** 2f closed by #48

**Comment by IssamT** [comment]
Are we adding the tests in linearproginterface 2-a and 2-b? (We can t change the UB or LB of all constraints)

**Comment by joaquimg** [comment]
We could do that for `VectorAffineFunction` in `Nonnegatives/Nonpositives/Zeros`

**Comment by joaquimg** [comment]
**linproginterface.jl** 1d and 1e closed by #53 and #55

**Comment by odow** [comment]
**linprog.jl** c,d,e are in #103

**Comment by odow** [comment]
Ported to MOIT
