### ISSUE TITLE
Decision on ListOfVariableIndices

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/MathOptInterface.jl#230]
The documentation now is pretty sparse:

> A Vector{VariableIndex} indexing all variables present in the model (i.e., of length equal to the value of NumberOfVariables()).

We should either 1) make a big point here about the variables in the list appearing in an arbitrary order or 2) define an ordering on the variables. I would propose to enforce that `ListOfVariableIndices` returns variables ordered by creation time, because:
- Most wrappers do this anyway.
- It matches user expectations.
- In the worst case the model needs to maintain an extra ordered set.

Ref https://github.com/JuliaOpt/MathOptInterface.jl/pull/226

**Comment by odow** [comment]
I vote 2)

**Comment by blegat** [comment]
I am also in favor of 2). We should also add that the order is preserved under `copy!`.

**Comment by IssamT** [comment]
+1 for 2)

**Comment by joaquimg** [comment]
2) it is!
