### ISSUE TITLE
A File-format for MathOpt

### ISSUE THREAD

**Issue by odow** [JuliaOpt/MathOptInterface.jl#28]
Here's a potentially naive question (considering I know nothing about conic): 

Is it possible to save any problem (based on the current standard form with linear-quadratic functions, and the current sets) in the CBF format? 

Because I was reading through the specification (incl. the new one http://cblib.zib.de/doc/format2.pdf) and it wasn't obvious to me how to have quadratic objectives/quadratic terms in the constraints.

It seems like if this is to be **the standard form** that unifies linear/conic etc, it would be nice to have one simple, easy to parse file-format that everybody agrees upon (unlike LP and MPS where nobody agrees on a canonical format and each reader/writer has weird limitations).

**Comment by chriscoey** [comment]
It's not possible with CBF, no. It was designed for LP/SOCP/SDP storage, and later was extended to also allow exponential cones (3 dimensional: z >= y exp(x/y)). It is affine expression in cone only, and Henrik will likely want to keep it conservative like that.

It is worth starting a new issue to discuss a storage format. I don't think it's high on the list of priorities but if there is a simple solution then perhaps it should be.

**Comment by odow** [comment]
Excellent. This is high on my list of priorities, but I didn't want to JuMP (if you will) the gun if the CBF can already do it.

**Comment by mlubin** [comment]
CBF is a good conceptual starting point, but it's designed for conic and doesn't support quadratic terms, as @chriscoey explained. I'd argue for keeping things simple to start out, and just serializing an [`Instance`](https://github.com/JuliaOpt/MathOptInterface.jl/issues/9) type using [`JLD(2)`](https://github.com/simonster/JLD2.jl) if you're looking for intermediate storage. Long-term storage of instances in MOI format doesn't seem like the best idea at this point since we could easily decide to change the structures of the sets or functions before MOI 1.0.

**Comment by odow** [comment]
I'm not looking to save MOI objects in julia. But some general mathematical optimisation problem in a language agnostic way. The question is how general to make that. MPS and LP both have limitations. It's seems that the MOI general form is quite nice so it seems like a good starting point.

**Comment by mlubin** [comment]
I agree that MOI would correspond well with a language-agnostic file format. It just seems premature to start storing instances in this format because MOI will be changing.

**Comment by mlubin** [comment]
As mentioned in https://github.com/JuliaOpt/MathOptInterface.jl/pull/132, I'm going to be playing around with serializing MOI instances. The goal is to be able to write small instances to a human readable text format and use these in JuMP's tests to make sure it constructs the correct model without needing a solver. They could also be used in solvers' tests. Currently thinking JSON.

**Comment by odow** [comment]
Yes I had a play with this a while ago. Json works very well. A list of constraints. Each constraint is an object from a predefined list of sets with parameters. I'm on the farm ATM but will be back at work and my computer tomorrow.

**Comment by mlubin** [comment]
I'd structure it with a predefined list of functions and a predefined list of sets that you can mix and match to keep it closer to the original MOI. If you have some code already written would be happy to take a look.

**Comment by odow** [comment]
I don't think I got around to writing any code but I started (very much the operative word) a document with some specs
[Mathematical_Optimization_Format.pdf](https://github.com/JuliaOpt/MathOptInterface.jl/files/1328031/Mathematical_Optimization_Format.pdf)

**Comment by mlubin** [comment]
I like it, can we chat more?

**Comment by odow** [comment]
You're on east coast time yeah? I can do anytime Tuesday or Wednesday EST. Don't mind waking up so pick whatever works. After Wednesday I'm going to Australia for a few days so it'll have to be next week

**Comment by joaquimg** [comment]
What about TOML? They are being used in pkg3.

**Comment by odow** [comment]
We've made some progress in https://github.com/odow/MathOptFormat.jl

Feedback solicited.

**Comment by joaquimg** [comment]
Where its better to talk? Here? There? A gitter room?

**Comment by odow** [comment]
Best to open an issue over there.

**Comment by blegat** [comment]
It would be nice to be able to directly write the Gurobi optimizer. We would need to dispatch on a third argument being the file extension though.

**Comment by blegat** [comment]
@odow Is this resolved ?

**Comment by odow** [comment]
What do you think about adding MOF as a submodule to MOI?

**Comment by rschwarz** [comment]
I guess that means submodule in the Julia sense, not git sense.
