### ISSUE TITLE
CachingOptimizer modifyconstraint! performance

### ISSUE THREAD

**Issue by tkoolen** [JuliaOpt/MathOptInterface.jl#321]
I'm a little worried about the performance of `modifyconstraint!` with `CachingOptimizer`. Maybe the point of worrying about performance hasn't been reached yet, but I still wanted to bring this to your attention.

Here's an example:

```julia
using BenchmarkTools
using OSQP.MathOptInterfaceOSQP
const MOI = MathOptInterface
const MOIU = MOI.Utilities

optimizer = OSQPOptimizer()
MOI.set!(optimizer, OSQPSettings.Verbose(), false)
caching_optimizer = MOIU.CachingOptimizer(OSQPModel{Float64}(), optimizer);
v = MOI.addvariables!(caching_optimizer, 2)
cf = MOI.ScalarAffineFunction(v, [0.0, 0.0], 0.0)
c = MOI.addconstraint!(caching_optimizer, cf, MOI.Interval(-Inf, 1.0))
```

With no optimizer attached:

```julia
julia> @btime MOI.modifyconstraint!($caching_optimizer, $c, $(MOI.Interval(0.0, 2.0)))
  133.940 ns (7 allocations: 176 bytes)
```

With optimizer attached:

```julia
julia> MOIU.attachoptimizer!(caching_optimizer);
julia> @btime MOI.modifyconstraint!($caching_optimizer, $c, $(MOI.Interval(0.0, 2.0)))
  322.491 ns (12 allocations: 272 bytes)
julia> @btime MOI.modifyconstraint!($(caching_optimizer.model_cache), $c, $(MOI.Interval(0.0, 2.0))); # for the record
  26.208 ns (3 allocations: 96 bytes)
```

while for the raw optimizer:

```julia
julia> @btime MOI.modifyconstraint!($(caching_optimizer.optimizer), $(caching_optimizer.model_to_optimizer_map[c]), $(MOI.Interval(0.0, 2.0)))
  11.927 ns (0 allocations: 0 bytes)
2.0
```

I think there are a few opportunities to improve performance:

1. Parameterize `CachingOptimizer` on the types of `model_cache` and `optimizer` (i.e., `CachingOptimizer{M<:MOI.ModelLike, O<:MOI.AbstractOptimizer}`). These fields are currently abstractly typed, so any interaction with them will cause runtime dispatch and allocations. This would mean that the current approach of setting the `optimizer` field to `nothing` to detach the optimizer has to be implemented in a different way.
1. Improve the performance of `IndexMap`. Indexing into an `IndexMap` is definitely a performance hotspot, so the fact that the `conmap` field is a `Dict` with abstract key and value types should probably be addressed. Also, `Dict` is pretty slow anyway. If constraint indices were unique, `IndexMap` could be reimplemented using a CardinalDict (https://github.com/JeffreySarnoff/CardinalDicts.jl), which would probably be a lot faster.
1. Stop using `@assert`. `@assert` has a small performance penalty associated with it that makes it unsuitable for low level functions.

Just some suggestions of course. What do you think?

**Comment by mlubin** [comment]
These are good points, thanks for bringing them up. Without responding specifically yet, I'll say at at high level that I'm most concerned at this point about design issues in either MOI or the JuMP user-facing API that would prevent us from getting good performance in the future. Also we may advise performance-conscious users to try and skip `CachingOptimizer` if possible, but it would be nice if the gap wasn't nearly 30x for a function call as you demonstrate here.

**Comment by tkoolen** [comment]
> Also we may advise performance-conscious users to try and skip `CachingOptimizer` if possible

Yeah, that's what I'm leaning towards. I'm still trying to decide whether in my case it will be worth it to use JuMP  to set up the initial problem and then call `modifyconstraint!` on the `OSQPOptimizer` after the `MOI.copy!`, or to just work at the MOI level from the beginning, since I have to work with `VariableIndex` and `ConstraintIndex` to do the modifications anyway. In any case, it's good to have this choice available.

**Comment by blegat** [comment]
@tkoolen Thanks for looking into this !
Parametrizing on the `model_cache` might be an easy first step as it is present in every constructor. Parametrizing in the `optimizer` is more tricky as its type is not known in the constructor `CachingOptimizer(model_cache::MOI.ModelLike, mode::CachingOptimizerMode)` and this constructor is needed for JuMP to be able to have the `Model()` constructor.

**Comment by mlubin** [comment]
@tkoolen if you're thinking of working at the MOI level, consider using [direct mode](https://github.com/JuliaOpt/JuMP.jl/blob/f74f948495b0dd6d97f0ec45b54fc65c471f4ad6/src/JuMP.jl#L162) in JuMP which attaches the JuMP model directly to optimizer. We obviously intend to provide a JuMP-level interface to `modifyconstraint!`.

**Comment by blegat** [comment]
> JuMP user-facing API that would prevent us from getting good performance in the future

In view of the substantial improvement obtained by parametrizing the type in https://github.com/JuliaOpt/MathOptInterface.jl/pull/323, we might consider removing the `NoOptimizer` mode and the constructor `CachingOptimizer(::MOI.ModelLike, ::CachingOptimizerMode)` that does not contain an optimizer.

For the JuMP `Model()` constructor, it can simply do `moibackend = JuMPModel{Float64}()` and then when an optimizer `optimizer` is attached, it does `moibackend = CachingOptimizer(moibackend, optimizer)`.
That way way, only the `moibackend` field is not a concrete type.

If we do that, we need to remove the `dropoptimizer!` function. Then we might also rename `resetoptimizer!` to `detachoptimizer!`, which has a consistent name with `attachoptimizer!`.
