### ISSUE TITLE
Default ObjectiveSense

### ISSUE THREAD

**Issue by odow** [JuliaOpt/MathOptInterface.jl#335]
Should we enforce one? If so, which?

Ref #329

**Comment by odow** [comment]
Bump. What does it mean to solve a model without setting `ObjectiveSense`? Is it solver-specific?

**Comment by mlubin** [comment]
Let's make `FeasibilitySense` the default and move on.

**Comment by blegat** [comment]
I agree with `FeasibilitySense` by default

**Comment by blegat** [comment]
This is causing Mosek to fail when there is no objective since it queries the `ObjectiveSense` but the model says it cannot be gotten
