### ISSUE TITLE
The set Reals

### ISSUE THREAD

**Issue by odow** [JuliaOpt/MathOptInterface.jl#355]
Why do we have a set [Reals](http://www.juliaopt.org/MathOptInterface.jl/latest/apireference.html#MathOptInterface.Reals)? Are any solvers expected to implement this? What does it even mean?

**Comment by joaquimg** [comment]
There are aplications where its interesting to switch constraints on and off instead of adding amd deleting. Maybe changing the set is a way to go.

**Comment by blegat** [comment]
We are currently biased towards LP solvers which assume by default that variables are Reals but for a constraint programming solver, it is more natural to assume by default that variables are Integer. Maybe we should add `Reals`  constraints in the tests (or even ask for a set in the `addvariable!` function).

**Comment by mlubin** [comment]
LP solvers support "free" constraints, so `Reals` isn't that unnatural. I don't see it as high priority to support, however.

> or even ask for a set in the `addvariable!` function

We decided against doing this when designing MOI, why go back? It's entirely redundant with `SingleVariable` + set constraints.

**Comment by odow** [comment]
The general consensus seems to be that we should leave it.
