### ISSUE TITLE
Length of MOI function

### ISSUE THREAD

**Issue by blegat** [JuliaOpt/MathOptInterface.jl#366]
There is currently a function `MOIU.moilength` to get the length of a function. The name isn't nice though. How should it be named ?
* `output_length` (see https://github.com/JuliaOpt/MathOptInterface.jl/pull/364#discussion_r189433282)
* `dimension`

We could also move it to MOI to be consistent with `MOI.dimension(::MOI.AbstractSet)`

**Comment by mlubin** [comment]
If we're going with dimension, what about `output_dimension`?

**Comment by blegat** [comment]
`dimension` would be ambiguous for a function but `output_dimension` is clear and is consistent with the set function, I like it
