### ISSUE TITLE
Likely persistent annoyances with 32 bit support due to explicit `Int64`s

### ISSUE THREAD

**Issue by tkoolen** [JuliaOpt/MathOptInterface.jl#377]
Explicit `Int64`s, e.g. in these locations:

https://github.com/JuliaOpt/MathOptInterface.jl/blob/0b5afa2b32fa76f3e5bb203f077e6891a9bd1ffb/src/functions.jl#L86-L89

https://github.com/JuliaOpt/MathOptInterface.jl/blob/0b5afa2b32fa76f3e5bb203f077e6891a9bd1ffb/src/functions.jl#L154-L157

are pretty likely to cause headaches with trying to support 32 bit architectures. I ran into this already in https://github.com/oxfordcontrol/OSQP.jl/pull/14.

I personally don't think it would be so bad to have those fields just be `Int`s, as more than two billion rows (`typemax(Int32)`) in one `VectorAffineConstraint` seems like an uncommon scenario, but I think at least there should be constructors for these types that take `Integer`s.

**Comment by mlubin** [comment]
I don't see a good reason for the definition of MOI functions to change based on the platform. That would make serialization more complicated, for example. Restricting everything to `Int32` would create the same inconvenience on 64-bit platforms and seems short-sighted. I support helper constructors to address this.

**Comment by tkoolen** [comment]
Note that `linear7test` is broken on 32 bit platforms because of this.

https://github.com/JuliaOpt/MathOptInterface.jl/blob/0b5afa2b32fa76f3e5bb203f077e6891a9bd1ffb/src/Test/contlinear.jl#L946

**Comment by joaquimg** [comment]
As a observation, Xpress has update its C interface to support more than `maxtype(Int32)` constraints. (They do highlight that most models with this size wont be solvable).
I don't think we should block this if its not extremely important.
