### ISSUE TITLE
Caching optimizer: Reset state::CachingOptimizerState when changing model_cache::MT

### ISSUE THREAD

**Issue by vitornesello** [JuliaOpt/MathOptInterface.jl#395]
I am implementing an MOI interface for and Cbc.jl using cachingOptimizer, but I cannot pass some tests ("linear1test" in contlinear.jl) because when model_cache is updated, state::CachingOptimizerState is not changed.

So if I optimize my problem for the first time (state = EmptyOptimizer):

``` julia
function MOI.optimize!(m::CachingOptimizer)
    if m.mode == Automatic && m.state == EmptyOptimizer
        copy_result = attachoptimizer!(m)
        end
    end
    # TODO: better error message if no optimizer is set
    @assert m.state == AttachedOptimizer
    MOI.optimize!(m.optimizer)
end
```
it will execute attachoptimizer!(), which changes the value of state to AttachedOptimizer then run the optimization. But if I modify the problem, lets say by adding a variable:

``` julia
function MOI.addvariable!(m::CachingOptimizer)
    # Same note as for addconstraint!
    if m.mode == Automatic && m.state == AttachedOptimizer && !MOI.canaddvariable(m.optimizer)
        resetoptimizer!(m)
    end
    vindex = MOI.addvariable!(m.model_cache)
    if m.state == AttachedOptimizer
        vindex_optimizer = MOI.addvariable!(m.optimizer)
        m.model_to_optimizer_map[vindex] = vindex_optimizer
        m.optimizer_to_model_map[vindex_optimizer] = vindex
    end
    return vindex
end
```

and call optimize! again, it will not execute attachoptimizer!() again because the value of state is still set to AttachedOptimizer, thus solving the same problem as previously.

**Comment by mlubin** [comment]
Please chat with @IssamT before going too far in this direction.

**Comment by vitornesello** [comment]
@mlubin Sorry, I expressed myself badly. I am using cachingOptimizer just to run contlinear tests. The wrapper itself does not use cachingOptimizer at all. I have implemented copy! as suggested by you.

``` julia
const optimizer = MOIU.CachingOptimizer(ModelForCachingOptimizer{Float64}(), CbcOptimizer())
const config = MOIT.TestConfig(atol=1e-4, rtol=1e-4, duals = false, infeas_certificates = false)

@testset "Continuous linear problems" begin
    MOIT.contlineartest(MOIB.SplitInterval{Float64}(optimizer), config)
end
```

**Comment by mlubin** [comment]
Ah, ok! 

Why doesn't this condition trigger inside the call to `addvariable!`?
```julia
if m.mode == Automatic && m.state == AttachedOptimizer && !MOI.canaddvariable(m.optimizer)
    resetoptimizer!(m)
end
```

**Comment by vitornesello** [comment]
You are right, it was another mistake in my part of the code. Now I have only 12 fails in contlinear.jl. Thanks!
