### ISSUE TITLE
Problems with transform!

### ISSUE THREAD

**Issue by odow** [JuliaOpt/MathOptInterface.jl#398]
The following are unresolved after https://github.com/JuliaOpt/MathOptInterface.jl/pull/388

- [ ] `cantransform` still takes the instance of the constraint index of an argument rather than the type. This is needed because there is a default fallback and `candelete` also takes the instance rather than the type. (See another instance of this inconsistency with `candelete`: #218.)
- [x] `transform!` is not tested as it is not implemented in `MockOptimizer`.
- [ ] `transform!` only applies to constraint sets. Should it apply to constraint functions for consistency? I'm not sure if it makes sense to change the function to a different  type of function without deleting the constraint though...

**Comment by blegat** [comment]
> `transform!` is not tested as it is not implemented in `MockOptimizer`

There is the fallback so it does not need to implement it, does it ?

**Comment by odow** [comment]
Closing as `cantransform` has been removed, `transform` is tested, and we agreed that `transform` should only apply to sets.
