### ISSUE TITLE
ScalarLinearFunction and redundancy with scalar constraints

### ISSUE THREAD

**Issue by joaquimg** [JuliaOpt/MathOptInterface.jl#40]
We have the following table in the manual:

#### Linear constraints

| Mathematical Constraint       | MOI Function                 | MOI Set       |
|-------------------------------|------------------------------|---------------|
| ``a^Tx \le u``                | `ScalarAffineFunction`       | `LessThan`    |
| ``a^Tx \ge l``                | `ScalarAffineFunction`       | `GreaterThan` |
| ``a^Tx = b``                  | `ScalarAffineFunction`       | `EqualTo`     |
| ``l \le a^Tx \le u``          | `ScalarAffineFunction`       | `Interval`    |
|...                |... | ...    |

In the first four lines we use `a^Tx` in the first column and we say `ScalarAffineFunction`, should we say/use `ScalarLinearFunction`? This could avoid multiple representations of the same constraint. Since `a^Tx - b = 0` is equivalent to `a^Tx = b`

**Comment by mlubin** [comment]
@joaquimg, that would require introducing a new category of function. We can't get rid of `ScalarAffineFunction` because it's needed for conic constraints. And then we'd have the question of if solvers should support both `ScalarAffineFunction` and `ScalarLinearFunction` in `LessThan` or just `ScalarLinearFunction` in `LessThan`. 
I'm okay with the potential for redundancy here.

**Comment by mlubin** [comment]
Well, to be more precise, `VectorAffineFunction` is needed for conic constraints. It seems a bit inconsistent though to have `ScalarLinearFunction` and `VectorAffineFunction`.

**Comment by mlubin** [comment]
`ScalarAffineFunction` is useful for handling constants in the objective function

**Comment by joaquimg** [comment]
Sure, I don´t think we should get rid of `ScalarAffineFunction`. However, since scalar constraints have their own sets (`Interval`, `LessThan` ...) they could have their own function and we disallow `ScalarAffineFunction` only for them...

**Comment by mlubin** [comment]
What's the difference between introducing ``ScalarLinearFunction`` and letting solvers choose to reject ``ScalarAffineFunction``s when the constant is not zero?

**Comment by joaquimg** [comment]
Querying and modifying these scalar constraints might be a bit "degenerate" and would add more complexity on the solver api side...

**Comment by joaquimg** [comment]
I am fine with rejecting `ScalaAffineFunction` when the constant is not zero

**Comment by mlubin** [comment]
It doesn't bother me if solvers choose to not support this case.

**Comment by joaquimg** [comment]
But you think that would be solver dependent?

**Comment by IssamT** [comment]
A minor related issue:

For some reason, we have 

```julia
modifyconstraint!(m::AbstractSolverInstance, c::ConstraintReference, change::AbstractFunctionModification)
```

But we don't have

``` 
modifyconstraint!(m::AbstractSolverInstance, c::ConstraintReference, change::AbstractSetModification)
```

So if the solver wants to have a specific behavior if only the right hand side (the constant) of a linear constant has been modified, it is now only possible if the constant is encoded in the `ScalaAffineFunction` and not in the `LessThan` / `GreaterThan` set.

**Comment by mlubin** [comment]
@IssamT there's no ``AbstractSetModification`` because all of the existing sets are very lightweight and have little data. You're allowed to replace the set entirely (with another set of the same type).

**Comment by mlubin** [comment]
@IssamT if you encode your constraint in the form ``Ax + b \in nonnegative`` then you can modify the constant part of the function to achieve changing the right-hand side.

**Comment by mlubin** [comment]
@joaquimg, I see MOI as a marketplace for solvers and users to come together and agree on how to encode the problem. MOI is very general and I expect that we'll converge to practical conventions like not supporting constant terms combined with `LessThan`, `GreaterThan`, and `EqualTo`.

**Comment by IssamT** [comment]
> there's no AbstractSetModification because all of the existing sets are very lightweight and have little data. You're allowed to replace the set entirely (with another set of the same type).

But it means that the solver needs to check if the set was of the same type before the modification (GreaterThan before and after) to discover that it was only a constant change.

**Comment by mlubin** [comment]
@IssamT, a set can *only* be replaced with another of the same type.

**Comment by IssamT** [comment]
Nevermind. I have already been trapped by it twice today :)

**Comment by IssamT** [comment]
If different possible representation of the same thing bothers you, does the convention of not supporting constant terms combined with LessThan, GreaterThan, and EqualTo help?

f used with LessThan is the same as -f used with GreaterThan

**Comment by IssamT** [comment]
it is not the same for the duals though...

**Comment by mlubin** [comment]
@IssamT it's all up to the discretion of who's writing the solver interface and how much complexity they want to deal with

**Comment by IssamT** [comment]
According to this :

http://web.stanford.edu/class/ee364a/lectures/problems.pdf

(slide 2) 

LessThan and EqualTo seems to be enough

**Comment by joaquimg** [comment]
Actually only `LessThan` is enough, but we want to keep it flexible as miles said.

**Comment by mlubin** [comment]
It's enough to annoy users also. I don't plan on removing ``>=`` from JuMP, for example.
Not allowing constants in the affine parts doesn't seem very annoying since it's not so natural anyway.

**Comment by IssamT** [comment]
LessThan is not enough I think for dual representation. In our solver we have only LinearExpr <= constant. but we still use JuMP and reformulate the constraint on the solver side

**Comment by mlubin** [comment]
Don't forget that `LessThan` and `GreaterThan` are also used for variable bounds.

**Comment by IssamT** [comment]
we treat bounds separately but that s not an issue. I think it is important to have a clear decision on this question: 

Is MOI an interface with the solvers only or is it both a lower and higher interface? 

if someone will directly use MOI to write his model then the answer to many issues will be different.

**Comment by mlubin** [comment]
It is both a lower and higher-level interface because users will have the ability to specify MOI constraints from jump, e.g.,
```julia
@constraint(m, A*x + b in SecondOrderCone(n))
```
I have no plans to implement a transformation layer in JuMP, so whatever solvers support will correspond to what users can write down.

**Comment by mlubin** [comment]
If a solver chooses not to support ``ScalarAffineFunction`` in ``GreaterThan`` then users will not be able to write
```julia
@constraint(m, dot(a,x) >= b)
```

**Comment by IssamT** [comment]
Or we can have a transformation layer in MOI. For example MOI defines GreaterThan using LessThan. so that solvers only implement LessThan, unless they choose to reimplement GreaterThan. We can put the optional functions in a separate file and document this since julia doesn't offer good tools for clean definitions of interfaces.

**Comment by mlubin** [comment]
@IssamT, I'm open to a proposal on that, but I don't have a good picture of what it would look like. The problem is not only translating the constraint but also translating back the constraint primal and constraint dual.

**Comment by joaquimg** [comment]
I think we got off topic. To summarize what we talked about in this issue should we add to the manual that some solver (or all of them), might reject constant therm in scalar constraints? or we leave it as is?

**Comment by mlubin** [comment]
@joaquimg, you're welcome to add a sentence to the "Implementing a solver interface" section that it's reasonable to reject these constraints

**Comment by IssamT** [comment]
I know how hard it can be to even support both Min and Max when the solver has only Min. So yea this is possible but not easy. Anyway I think if we ever decide at some point to provide some default shortcuts for solvers we can add them without breaking the interface. so better keep the interface generic for now. 

@joaquimg you can claim that we are off topic and answer every single issue separately or you can push the discussion once to a conclusion and close all other issues with simple reference to the 1st issue.

**Comment by mlubin** [comment]
The question of transformations is a very big one and will not be resolved in this issue

**Comment by blegat** [comment]
@IssamT We discussed about your idea [here](https://github.com/JuliaOpt/MathProgBase.jl/issues/186).

**Comment by IssamT** [comment]
@mlubin I agree with you and wasn't planning to solve it here. 
@blegat thank you for the reference.

If you don't mind guys, I suggest to put in the documentation a more general conclusion:

Solvers might reject redundant representations of the same mathematical problem. Such redundancy exist in MathOptInterface for the following reasons

- MathOptInterface is in itself a highlevel interface. 
- Its functions, that are implemented by the solvers, are called by JuMP without transformation.
- This is non-blocking for future transformations that are made at the level of MathOptInterface (solvers will just need to allow what they may be denying at that point)

**Comment by IssamT** [comment]
The last point may be kept just in the issue

**Comment by mlubin** [comment]
@IssamT, I generally agree. Please open an issue so we don't forget to update the manual
