### ISSUE TITLE
Aliasing some parameteric types

### ISSUE THREAD

**Issue by mohamed82008** [JuliaOpt/MathOptInterface.jl#414]
I think it is a good idea to have aliases for things like `ConstraintIndex{ScalarAffineFunction{Float64},LessThan{Float64}}`. Some suggestions: `LinEqIndex{T}`, `LinLeqIndex{T}`, `LinGeqIndex{T}`, adding `s` for the vector versions: `LinEqsIndex{T}`, `LinLeqsIndex{T}`, `LinGeqsIndex{T}` for example. Opinions?

**Comment by mohamed82008** [comment]
PR or close the issue?

**Comment by mlubin** [comment]
I don't think we have a consensus on this yet. It will depend on an upcoming discussion in the style guide on which abbreviations we want to allow.

**Comment by blegat** [comment]
Closing as stale. The shortcuts are usually specific to the package using MOI so it's not clear that we should add anything in MOI itself.
