### ISSUE TITLE
`something` not defined

### ISSUE THREAD

**Issue by mohamed82008** [JuliaOpt/MathOptInterface.jl#421]
I am getting ` UndefVarError: something not defined` when running the tests.

https://github.com/JuliaOpt/MathOptInterface.jl/blob/247c4baf673eb8b1c29177e7f1652a0a78e1d570/src/Utilities/functions.jl#L310

**Comment by odow** [comment]
Ref https://github.com/JuliaLang/julia/pull/27258

You'll need to do something with `Compat`.

**Comment by mohamed82008** [comment]
Thanks. I needed to manually checkout latest `Compat`, my `Pkg` is clinically dead.
