### ISSUE TITLE
Removing can... functions

### ISSUE THREAD

**Issue by blegat** [JuliaOpt/MathOptInterface.jl#423]
After a long discussion with @odow and @mlubin . We plan to remove the `canset`, `canaddconstraint`, `canaddvariable`, `canmodify`, `cantransform`, `candelete` functions in favor of throwing an error during `set!`, `addconstraint!`, ...
The CachingOptimizer is using these methods in `Automatic` mode to see if it should change from the `AttachedOptimizer` state to the `EmptyOptimizer` state automatically because the optimizer cannot do the modification in its currently state even it supports it (so by being emptied and then having the model recopied before optimization, it could work).
Instead of using these `can...` functions, the CachingOptimizer will do the `set!`, `addconstraint!`, ... in a `try`-`catch` and detach the optimizer automatically if it throws an error mentioning it cannot handle the operation in its current state.
This `try` `catch` seems to have a fixed 10 ns cost in our benchmark so it shouldn't be noticeable for most usage.
The `Manual` mode won't do any `try`-`catch` so it can be used if someonce needs to use the CachingOptimizer but do not want this 10 ns penalty for every operation.

This would resolve https://github.com/JuliaOpt/MathOptInterface.jl/issues/295, https://github.com/JuliaOpt/MathOptInterface.jl/issues/218, https://github.com/JuliaOpt/MathOptInterface.jl/pull/357#issuecomment-388685219

The `CopyResult` will also disappear and will be replaced by the exceptions thrown by the `set!`, `addconstraint!`, ... calls

This would resolve https://github.com/JuliaOpt/MathOptInterface.jl/issues/243

**Comment by blegat** [comment]
There is a last remaining issue with names where `canset` is used to determine if a name is already in use. What is the replacement for this ?

**Comment by rdeits** [comment]
Is there a standard error that will be thrown when the `get/set!/etc.` fails?

**Comment by mlubin** [comment]
Yes, standard exceptions for unsupported operations are part of this redesign. We want to distinguish `get`/`set!` calls that should fail because the solver doesn't support the operation, and other errors (e.g., bugs in the wrapper) that should propagate up instead of silently being caught.

**Comment by rdeits** [comment]
Ok, sounds great, thanks
