### ISSUE TITLE
capitalization of solver names

### ISSUE THREAD

**Issue by chriscoey** [JuliaOpt/MathOptInterface.jl#425]
**First** (and most importantly): let's use consistent capitalization _within_ solver packages. CPLEX.jl does not - I always forget whether to write
```
using CPLEX
solver = CplexSolver()
```
or 
```
using Cplex
solver = CPLEXSolver()
```
and have to go look it up. Knitro/KNITRO is also inconsistent. Others too probably but I didn't check them all. In "MathOptInterfaceCPLEX.jl", which seems dead at the moment, "CPLEXOptimizer" is used - that fixes the internal consistency issue there at least.

**Second** (and less importantly): let's have consistency _across_ different solver packages. On the MOSEK website, it seems the name is officially "MOSEK", yet Mosek.jl uses a consistent "Mosek". For CBC (Coin Branch & Cut), Cbc.jl uses a consistent "Cbc". Similarly for CLP. So maybe we should use "Cplex", "Ecos", "Scs", "Csdp", "Knitro" etc. Why should Cbc and Clp and Mosek be not in all caps when these other packages are? So it would be nice to stick to a convention. I think I have prefer not all caps - so keep "Cbc" and "Clp" and "Mosek" and change "CPLEX" etc.

**Comment by blegat** [comment]
We might kill 2 birds with 1 stone if we say that the optimizer name should be the unexported `Optimizer`. So to use CPLEX optimizer we should do CPLEX.Optimizer. If a package want to create several optimizers, it can have submodules and have a `Optimizer` per submodule. E.g. `GLPK.LP.Optimizer`. What do you think ?

**Comment by chriscoey** [comment]
@blegat if it's feasible, sounds very good to me. that addresses the first point of internal consistency.

thoughts on the second point? "GLPK" or "Glpk"?

**Comment by odow** [comment]
Cplex is dead because it evolved into linquadoptinterface.jl. I have no immediate plans to revive it.

I agree with Benoît, packages should implement the unexported Optimizer.

**Comment by blegat** [comment]
I like full capitals when it is an acronym like GLPK but I don't think this is a good rule.
Why don't we say: use capitals when you spell it as separate letters like G-L-P-K and use lower case when you spell it as a word like Gurobi and Mosek. The issue with this rule it should be CPlex since the C is spelled as a separate which is weird.
Maybe the best is to capitalize the same way the name of the solver is capitalized on the official website but that means the Mosek package should be capitalized.
@ulfworsoe why isn't the Mosek package name "MOSEK.jl" ?

**Comment by ulfworsoe** [comment]
GLPK is an acronym but Mosek is just a name. The Mosek logo is all caps, but we only use this convention in text and documentation (and tweets, apparently). So everywhere we use Mosek as a namespace name, module name or package name, we use either all lowercase "mosek" or "Mosek", depending on platform convention.

**Comment by chriscoey** [comment]
OK, I guess Knitro and Mosek are in a similar situation there.

Does anyone know why we named CBC "Cbc.jl" and CLP "Clp.jl"?

**Comment by mlubin** [comment]
It's not really our job to decide how to capitalize the solver names. But I agree that we should pick the version that the original developers prefer and use that version consistently within Julia.

I know that KNITRO was renamed to Artelys Knitro, which probably calls for renaming the package as well.

**Comment by odow** [comment]
I'm in favor of the convention `PackageName.Optimizer()`. 

For examples, see:
https://github.com/JuliaOpt/CSDP.jl/pull/27
https://github.com/JuliaOpt/GLPK.jl/pull/59

**Comment by chriscoey** [comment]
@odow `PackageName.Optimizer()` sounds like a good guideline/rule

**Comment by mlubin** [comment]
:+1:  for `PackageName.Optimizer()` whenever possible

**Comment by joehuchette** [comment]
+1
