### ISSUE TITLE
Inference issues with `broadcastvcat` cause MethodErrors

### ISSUE THREAD

**Issue by rdeits** [JuliaOpt/MathOptInterface.jl#426]
`MOI.get(::AbstractModel, ::MOI.ListOfConstraintIndices)` calls `broadcastvcat` on the internal model: https://github.com/JuliaOpt/MathOptInterface.jl/blob/851125c68541bfa7582eab3bf03aa84635114bcb/src/Utilities/model.jl#L272

However, it seems that that call is not always inferred correctly, which can result in the returned vector to be a `Vector{Any}`. This causes problems downstream here: https://github.com/JuliaOpt/MathOptInterface.jl/blob/851125c68541bfa7582eab3bf03aa84635114bcb/src/Utilities/copy.jl#L77

The issue is that `cis_src` is passed to `passattributes!`, which expects a `Vector{<:ConstraintIndex}`, not a `Vector{Any}`, and the result is a MethodError. 

I'll try to find a nice reproducible example and figure out what's causing the inference failure.

**Comment by blegat** [comment]
Closing as stale, the inference issue might have been fixed in Julia v1.0.
