### ISSUE TITLE
Improving canonicalization

### ISSUE THREAD

**Issue by rdeits** [JuliaOpt/MathOptInterface.jl#429]
Per some discussion on the jump-dev gitter, there are a number of places where it's easy to make mistakes in solver implementations when affine expressions have duplicate terms (that is, terms with the same variable index). We can remove any duplicates safely by calling `MOI.Utilities.canonical`, but the current version of that function is somewhat slow and allocates a lot of memory. I tried implementing a couple of options to improve it. 

The first idea is the one @mlubin  and I were discussing, using a Dict to hold the variable => coefficient mapping: 

```julia
struct DeduplicationCache{T}
    coefficients::Dict{MOI.VariableIndex, T}
    DeduplicationCache{T}() where {T} = new{T}(Dict{MOI.VariableIndex, T}())
end
function deduplicate_with_cache!(f::MOI.ScalarAffineFunction{T}, cache::DeduplicationCache) where {T}
    empty!(cache.coefficients)
    for term in f.terms
        cache.coefficients[term.variable_index] = term.coefficient + get(cache.coefficients, term.variable_index, zero(valtype(cache.coefficients)))
    end
    empty!(f.terms)
    for (var, coeff) in cache.coefficients
        push!(f.terms, MOI.ScalarAffineTerm(coeff, var))
    end
    f
end
function deduplicate_with_cache(f::MOI.ScalarAffineFunction, cache::DeduplicationCache)
    result = MOI.ScalarAffineFunction(copy(f.terms), f.constant)
    deduplicate_with_cache!(result, cache)
end
```

That turned out to perform worse than I was hoping, and it also doesn't sort the resulting variables so it can't replace `canonical()`. However, I also came up with a method more similar to the current `MOI.Utilities.canonical`, but doing all of its work in-place: 

```julia
function my_canonical(f::MOI.ScalarAffineFunction)
    result = MOI.ScalarAffineFunction(copy(f.terms), f.constant)
    my_canonical!(f)
end

function my_canonical!(f::MOI.ScalarAffineFunction)
    if length(f.terms) > 1
        sort!(f.terms, by=t -> t.variable_index.value, alg=QuickSort)
        i1 = 1
        i2 = 2
        while true
            if f.terms[i1].variable_index.value == f.terms[i2].variable_index.value
                f.terms[i1] = MOI.ScalarAffineTerm(f.terms[i1].coefficient + f.terms[i2].coefficient, f.terms[i1].variable_index)
                i2 += 1
            else
                f.terms[i1 + 1] = f.terms[i2]
                i1 += 1
                i2 += 1
            end
            if i2 > length(f.terms)
                break
            end
        end
        resize!(f.terms, i1)
    end
    f
end
```

Benchmarking the various approaches gives: 

### Julia v0.6.3

Time:

| n | MOI.Utilities.canonical | my_canonical | my_canonical! | deduplicate_with_static_cache | deduplicate_with_static_cache! |
| --- | --- | --- | --- | --- | --- |
| 10 | 2.017 μs | 929.000 ns | 894.000 ns | 4.207 μs | 1.299 μs  |
| 100 | 6.031 μs | 3.963 μs | 3.695 μs | 11.210 μs | 8.966 μs  |
| 1000 | 57.961 μs | 41.801 μs | 39.664 μs | 91.052 μs | 87.788 μs  |
| 10000 | 706.862 μs | 527.163 μs | 507.943 μs | 965.707 μs | 951.336 μs  |
| 100000 | 18.166 ms | 13.026 ms | 7.255 ms | 11.913 ms | 11.616 ms  |
| 1000000 | 172.884 ms | 164.866 ms | 85.844 ms | 232.217 ms | 224.895 ms  |
| 10000000 | 1.529 s | 1.011 s | 896.141 ms | 3.537 s | 3.410 s  |

Memory:

| n | MOI.Utilities.canonical | my_canonical | my_canonical! | deduplicate_with_static_cache | deduplicate_with_static_cache! |
| --- | --- | --- | --- | --- | --- |
| 10 | 896 bytes | 352 bytes | 112 bytes | 592 bytes | 320 bytes  |
| 100 | 5.34 KiB | 1.88 KiB | 112 bytes | 4.92 KiB | 3.13 KiB  |
| 1000 | 56.58 KiB | 15.86 KiB | 112 bytes | 47.03 KiB | 31.25 KiB  |
| 10000 | 491.66 KiB | 156.44 KiB | 112 bytes | 468.86 KiB | 312.50 KiB  |
| 100000 | 4.29 MiB | 1.53 MiB | 112 bytes | 4.58 MiB | 3.05 MiB  |
| 1000000 | 39.89 MiB | 15.26 MiB | 112 bytes | 45.78 MiB | 30.52 MiB  |
| 10000000 | 357.88 MiB | 152.59 MiB | 112 bytes | 457.76 MiB | 305.18 MiB  |

### Julia 0.7.0-beta2.43

Time: 

| n | MOI.Utilities.canonical | my_canonical | my_canonical! | deduplicate_with_static_cache | deduplicate_with_static_cache! |
| --- | --- | --- | --- | --- | --- |
| 10 | 456.000 ns | 284.000 ns | 240.000 ns | 3.825 μs | 1.152 μs  |
| 100 | 5.134 μs | 3.557 μs | 3.185 μs | 12.268 μs | 10.164 μs  |
| 1000 | 50.430 μs | 36.937 μs | 34.843 μs | 77.993 μs | 75.854 μs  |
| 10000 | 636.244 μs | 470.540 μs | 452.377 μs | 856.442 μs | 831.404 μs  |
| 100000 | 8.529 ms | 11.648 ms | 11.412 ms | 10.694 ms | 9.332 ms  |
| 1000000 | 107.026 ms | 139.062 ms | 138.975 ms | 265.215 ms | 196.011 ms  |
| 10000000 | 1.441 s | 915.029 ms | 1.121 s | 3.128 s | 2.987 s  |

Memory:

| n | MOI.Utilities.canonical | my_canonical | my_canonical! | deduplicate_with_static_cache | deduplicate_with_static_cache! |
| --- | --- | --- | --- | --- | --- |
| 10 | 528 bytes | 240 bytes | 0 bytes | 592 bytes | 320 bytes  |
| 100 | 4.98 KiB | 1.77 KiB | 0 bytes | 4.92 KiB | 3.13 KiB  |
| 1000 | 56.22 KiB | 15.75 KiB | 0 bytes | 47.03 KiB | 31.25 KiB  |
| 10000 | 491.30 KiB | 156.33 KiB | 0 bytes | 468.86 KiB | 312.50 KiB  |
| 100000 | 4.29 MiB | 1.53 MiB | 0 bytes | 4.58 MiB | 3.05 MiB  |
| 1000000 | 39.89 MiB | 15.26 MiB | 0 bytes | 45.78 MiB | 30.52 MiB  |
| 10000000 | 357.88 MiB | 152.59 MiB | 0 bytes | 457.76 MiB | 305.18 MiB  |

So it looks like the updated `my_canonical` function is faster than both the existing function and the Dict version. That's particularly nice because it means we don't have to bother with creating and hanging onto that Dict cache. 

Here's a gist to reproduce these results: https://gist.github.com/rdeits/713c3e1eddde8cdc4fee028b2bc0a98c

**Comment by rdeits** [comment]
One other question: is it OK to do the in-place canonicalization on an affine function that a user passes to `MOI.add_constraint!`? There's a huge benefit in memory allocation and a noticeable improvement in time from doing so, but I wonder if it's a good idea to modify that variable in-place.

**Comment by odow** [comment]
I think we agreed that solvers should not modify user input.

**Comment by rdeits** [comment]
In that case it's probably worth it to check if the function is already in canonical form before making a copy and doing the in-place operation, since frontends like JuMP and SimpleQP may already canonicalize their functions.

**Comment by mohamed82008** [comment]
I like the new implementation because it operates on the sorted vector instead of making a new one, and then throwing the sorted one away at the end, which the current implementation does. This explains the allocation difference.

**Comment by tkoolen** [comment]
Haha, that's funny, I just wrote a utility function that does almost the same thing, developed independently.

```julia
function combine!(a::Vector, combine, by, lt=isless)
    isempty(a) && return a
    sort!(a, QuickSort, Base.Order.ord(lt, by, false, Base.Sort.Forward))
    j = 1
    @inbounds for i in eachindex(a)[2 : end]
        x = a[i]
        if lt(by(a[j]), by(x))
            j += 1
            a[j] = x
        else
            a[j] = combine(a[j], x)
        end
    end
    resize!(a, j)
    a
end
```

Usage:
```julia
combinepair(x, y) = first(x) => last(x) + last(y)
n = 100

@test combine!([2 => 1.0, 2 => 2.0], combinepair, first) == [2 => 3.0]
@test combine!([3 => 1.0, 2 => 4.0, 3 => 2.0, 1 => 2.0], combinepair, first) == [1 => 2.0, 2 => 4.0, 3 => 3.0]
@test length(combine!(Pair.(1 : n, rand(n)), combinepair, first)) == n
@test length(combine!(Pair.(fill(3, n), rand(n)), combinepair, first)) == 1
```

Mine avoids the kwarg version of `sort!` for improved performance on 0.6.
