### ISSUE TITLE
More ObjectiveBound tests

### ISSUE THREAD

**Issue by blegat** [JuliaOpt/MathOptInterface.jl#442]
Is there a reason ObjectiveBound is currently only tested in one MIP test ?
Even for an LP with termination status Success and primal and dual status FeasiblePoint, ObjectiveBound should be accessible and give the value of the dual objective right ?
As a result of the lack of testing, ECOS was passing all the tests while not even implementing ObjectiveBound: https://github.com/JuliaOpt/ECOS.jl/pull/71

**Comment by odow** [comment]
> Even for an LP with termination status Success and primal and dual status FeasiblePoint, ObjectiveBound should be accessible and give the value of the dual objective right ?

Probably. But if you ask Gurobi for the objective bound of an LP, it returns `-1e100` for minimization problems.

**Comment by mlubin** [comment]
LP solvers are not very responsible about computing dual objectives but conic primal-dual solvers should be better. Maybe add this on a exp-cone and SDP problems? Worse case it's a test config option that solvers can disable if they prefer.

**Comment by odow** [comment]
Closed by #446.
