### ISSUE TITLE
Error types in objective modification 

### ISSUE THREAD

**Issue by rdeits** [JuliaOpt/MathOptInterface.jl#459]
Carried over from discussion on Gitter and https://github.com/oxfordcontrol/OSQP.jl/pull/25#discussion_r208277285

OSQP.jl supports objective function modifications, but only in certain states (i.e. when the model is not empty). So it seems like it would be useful to have a `CannotModifyObjective` exception that `modify!()` could throw.

**Comment by tkoolen** [comment]
Also, it was unclear to us whether to have

```julia
MOI.supports(::OSQPOptimizer, ::MOI.ObjectiveSense) = true
```

and/or what it should mean. Does it mean that you can get the objective sense (yes, you can), or set it (no, you can't for OSQP), or both?

**Comment by blegat** [comment]
It is only for setting. What do you mean you can't ? it assumes it is minimization ?

**Comment by blegat** [comment]
> Should that be "[...] supports setting [...]" then?

Yes

**Comment by blegat** [comment]
No, sorry, supports means it can be copied, i.e. you can do `MOI.copy! (model, src)` where src has the attribute in ListOf...AttributeSet.
