### ISSUE TITLE
Allow CachingOptimizer to set ConstraintSet

### ISSUE THREAD

**Issue by IssamT** [JuliaOpt/MathOptInterface.jl#463]
While updating Cbc to MOI v0.5.1, I found out that linear6 test is not passing. Cbc is tested using `CachingOptimizer` in `Automatic` mode. The test basically optimizes then tries to modify the `ConstraintSet` and it fails.

It looks to me that the reason is the new `replace_constraint_function_or_set!`. In v0.4.1 `resetoptimizer!(m)` was called, so the modification was done only on the cache and copy was called later on again. But in v0.5.1 it doesn't because the error thrown when trying to set the `ConstraintSet` in Cbc is `MOI.UnsupportedAttribute` instead of `MOI.CannotSetAttribute`.
 
Here is the function in v0.5.1
```julia
function replace_constraint_function_or_set!(m::CachingOptimizer, attr, cindex, replacement)
    if m.state == AttachedOptimizer
        if m.mode == Automatic
            try
                MOI.set!(m.optimizer, attr, m.model_to_optimizer_map[cindex], replacement)
            catch err
                if err isa MOI.CannotSetAttribute
                    resetoptimizer!(m)
                else
                    rethrow(err)
                end
            end
        else
            MOI.set!(m.optimizer, attr, m.model_to_optimizer_map[cindex], replacement)
        end
    end
    MOI.set!(m.model_cache, attr, cindex, replacement)
end
```

And here is the function in v0.4.1
```julia
function replace_constraint_function_or_set!(m::CachingOptimizer, attr, cindex, replacement)
    if (m.mode == Automatic && m.state == AttachedOptimizer &&
            !MOI.canset(m.optimizer, attr, typeof(cindex)) )
        resetoptimizer!(m)
    end
    MOI.set!(m.model_cache, attr, cindex, replacement)
    if m.state == AttachedOptimizer
        MOI.set!(m.optimizer, attr, m.model_to_optimizer_map[cindex], replacement)
    end
end
```

**Comment by IssamT** [comment]
maybe 

```julia
if err isa MOI.CannotSetAttribute
````
should be 

```julia
if err isa MOI.CannotSetAttribute || err isa MOI.UnsupportedAttribute
```

**Comment by IssamT** [comment]
maybe the function should be:

```julia
function replace_constraint_function_or_set!(m::CachingOptimizer, attr, cindex, replacement)
    if m.state == AttachedOptimizer
        if m.mode == Automatic
            if MOI.canset(m.optimizer, attr, typeof(m.model_to_optimizer_map[cindex])
                try
                    MOI.set!(m.optimizer, attr, m.model_to_optimizer_map[cindex], replacement)
                catch err
                    if err isa MOI.CannotSetAttribute
                        resetoptimizer!(m)
                    else
                        rethrow(err)
                    end
                end
            else
                resetoptimizer!(m)
            end    
        else
            MOI.set!(m.optimizer, attr, m.model_to_optimizer_map[cindex], replacement)
        end
    end
    MOI.set!(m.model_cache, attr, cindex, replacement)
end
```

**Comment by blegat** [comment]
`canset` has been removed, you should do something like https://github.com/JuliaOpt/ECOS.jl/pull/73/files#diff-3b39d17ea281f7c0a7e126ffc77935cfR94

**Comment by mlubin** [comment]
`set!` is documented to throw either `UnsupportedAttribute` or `CannotSetAttribute`, so at the minimum `replace_constraint_function_or_set!` should have a comment explaining why it doesn't catch `UnsupportedAttribute`.

**Comment by blegat** [comment]
Yes, we could add that

**Comment by IssamT** [comment]
Thanks @blegat. I can see why the following hack works, but I find it misleading. It doesn't really tell the truth about the solver. https://github.com/JuliaOpt/ECOS.jl/pull/73/files#diff-3b39d17ea281f7c0a7e126ffc77935cfR83

```julia
function MOI.supports(::Optimizer,
                      ::Union{MOI.ObjectiveSense,
                              MOI.ObjectiveFunction{MOI.ScalarAffineFunction{Float64}}})
    return true
end
function MOI.set!(::Optimizer,
                  attr::Union{MOI.ObjectiveSense,
                              MOI.ObjectiveFunction{MOI.ScalarAffineFunction{Float64}}},
                  value)
    throw(MOI.CannotSetAttribute(attr))
end
````
I believe the fix should be on the side of the `CachingOptimizer` while the solver throws `MOI.UnsupportedAttribute` because it is **stateless**.

**Comment by IssamT** [comment]
Sorry. I meant supports not can set in the suggested solution. Like this:

```julia
function replace_constraint_function_or_set!(m::CachingOptimizer, attr, cindex, replacement)
    if m.state == AttachedOptimizer
        if m.mode == Automatic
            if MOI.suppots(m.optimizer, attr, typeof(m.model_to_optimizer_map[cindex])
                try
                    MOI.set!(m.optimizer, attr, m.model_to_optimizer_map[cindex], replacement)
                catch err
                    if err isa MOI.CannotSetAttribute
                        resetoptimizer!(m)
                    else
                        rethrow(err)
                    end
                end
            else
                resetoptimizer!(m)
            end    
        else
            MOI.set!(m.optimizer, attr, m.model_to_optimizer_map[cindex], replacement)
        end
    end
    MOI.set!(m.model_cache, attr, cindex, replacement)
end
```

**Comment by blegat** [comment]
I agree that the `MOI.ConstraintSet` and `MOI.ConstraintFunction` are confusing attributes.
The current way they are handled is: they behave like classical attributes except:

* They never appear in `MOI.ListOfConstraintAttributesSet`

For this reason, the attributes are special because even if they are `MOI.set!` to the model cache and `MOI.set!` does not work for the optimizer, the model cache can still be copied to the optimizer.

However, even if the constraint functions and sets cannot be `MOI.set!`, they can still be `MOI.get`. For this reason, I initially considered every optimizer should support `MOI.ConstraintSet` and `MOI.ConstraintFunction` and we could add https://github.com/JuliaOpt/ECOS.jl/pull/73/files#diff-3b39d17ea281f7c0a7e126ffc77935cfR94 in MOI.
However, the definition of `UnsupportedAttribute` is really that it cannot be **set** so I think you are right and we should instead change the caching optimizer.

**Comment by IssamT** [comment]
What we have is a bit confusing now. I understand better the issue @blegat mentioned in the previous comment. Asking the question about a constraint of type ConstraintIndex{F,S} if it supports the attribute F or the attribute S (the types) is awkward. 

Maybe the Function/Set of a constraint (also the Function/Sense of an objective) should be separate concepts from attributes to avoid confusion. I see an MOI attribute as something that you attach to an object not as a part of its core definition. And we can have more clear functions such as `get_constraint_function(model, c::ConstraintIndex)` or `set_constraint_function(...)` this means that we would drop `supports` and keep only one kind of Exceptions : `CannotSetFunction/Set/Sense`

If we decide to keep them as attributes, I think @blegat's initial solution would be better: MOI would need to define `supports` for `MOI.ConstraintSet` and `MOI.ConstraintFunction` to return true or false based only on the type of the `ConstraintIndex` independently from the optimizer.

**Comment by blegat** [comment]
There are other attributes that are weird such as `NumberOfConstraints` which cannot be set can only be got so what is `MOI.supports(::ModelLike, NumberOfConstraints)` ? In think we can keep them as attributes.

However, we should replace
https://github.com/JuliaOpt/MathOptInterface.jl/blob/585a9593d9d093d60397de22295899b4d2aef6e1/src/attributes.jl#L55-L56
by
> In other words, it should return `false` if `copy!(model, src)` fails when the attribute is in the list of attributes set in `src`, i.e. [`MOI.ListOf...`](@ref), [`MOI.ListOf...`](@ref), ...
> `supports` does not need to be defined for attributes that cannot be set and for `MOI.ConstraintFunction` and `MOI.ConstraintSet` attributes since they do not appear in [`MOI.ListOfConstraintAttributesSet`](@ref).

And in
https://github.com/JuliaOpt/MathOptInterface.jl/blob/585a9593d9d093d60397de22295899b4d2aef6e1/src/attributes.jl#L511
we should add
> `MOI.ConstraintFunction` and `MOI.ConstraintSet` attributes should not be included in the list even if then have been set with `MOI.set!`.

**Comment by IssamT** [comment]
I'm a bit worried about defining `supports` only within the context of `copy!`. It should have a consistent meaning also outside the context of `copy!` as well.

**Comment by IssamT** [comment]
Shouldn't modifying a constraint using Function/Set change consistent with modifying a constraint by replacing the whole Function/Set ? There is no method to ask if an optimizer supports Function/Set change.

**Comment by blegat** [comment]
> I'm a bit worried about defining supports only within the context of copy!. It should have a consistent meaning outside the context of copy! as well.

With the removal of `canset`, there is no way to determine if a solver supports an operation. `supports` and `supportsconstraint` are related to copying, not to `MOI.set!` and `MOI.addconstraint!`. When `supports` or `supportsconstraint` return false, this means that even the CachingOptimizer cannot help (except for names since it does not copy names) so it need to be bridged.
For instance, `supportsconstraint` is used by `LazyBridgeOptimizer` to see if a constraint need to be bridged.
Similarly, `supports` for `ObjectiveFunction` could be use to bridge unsupported objective (but that's not done yet).

> Shouldn't "modifying a constraint using Function/Set change" consistent with "modifying a constraint by replacing the whole Function/Set" ? There is no method to ask if an optimizer supports Function/Set change.

Modification does not occur in `copy!` so there is no support function for that. A solver could only support `MOI.copy!` and support no other problem modification (neither addconstraint, set! or modify! or addvariable!)

**Comment by IssamT** [comment]
Thanks for the long explanation @blegat. It definitely helped me understand better the philosophy of all these methods. I will try to add more details in the documentation to help futur developers who might get confused by this. Just to sum up this discussion:

I thought that the following was a contradiction, because supports returns true, meaning there are situations where the optimizer is able to `MOI.set` this attribute, while `MOI.set` always throws `MOI.CannotSetAttribute`.

```julia
function MOI.supports(optimizer::Optimizer,
                      ::Union{MOI.ConstraintFunction,
                              MOI.ConstraintSet},
                      ::Type{<:CI})
    return true
end
function MOI.set!(optimizer::Optimizer,
                  attr::Union{MOI.ConstraintFunction,
                              MOI.ConstraintSet},
                  ::CI,
                  value)
    throw(MOI.CannotSetAttribute(attr))
end
````

But I was wrong. This is not a contradiction for two reasons.

1) An attribute such as `NumberOfConstraints` can be `MOI.get` only and not `MOI.set`.

2) (which is the one related to my example above) There might be ways of setting an attribute other than `MOI.set`. This is the case for a constraint Function/Set which are also "set" when the constraint is created.

Therefore my fix in #465 is in the wrong direction, and will only make this situation more confusing for other developers. 

So either we keep the current situation with only a better documentation which I am fine with, or if we want to clarify things programmatically we can avoid (either or both):

- the confusion of 1. by having supports_get and supports_set
- the confusion of 2. by considering the constraint Function/Set different from the other attributes. This would also avoid the inconsistency of having them as attributes but not putting them in `MOI.ListOfConstraintAttributesSet`

**Comment by IssamT** [comment]
Fixing 2. would require switching 

from:

```julia
function set!(model::ModelLike, attr::Type{<:AbstractFunction}, c::ConstraintIndex, value)
function set!(model::ModelLike, attr::Type{<:AbstractSet}, c::ConstraintIndex, value)
```

to:

```julia
function modify!(model::ModelLike, ci::ConstraintIndex{F, S}, new_function::F) where {F, S}
function modify!(model::ModelLike, ci::ConstraintIndex{F, S}, new_set::S) where {F, S}
```

**Comment by blegat** [comment]
That would be inverting @odow's PR https://github.com/JuliaOpt/MathOptInterface.jl/pull/388
We do not need a function to know if getting is supported as we do not need to get when copying. We only need support functions to know if copies are supported. We are moving away from can... functions

**Comment by IssamT** [comment]
For Gurobi, the RHS/Sense (Set) is treated as a constraint attribute but the LHS (Function) is not.

http://www.gurobi.com/documentation/8.0/refman/attributes.html

**Comment by mlubin** [comment]
Whatever change we adopt for constraints also has to apply for objectives, because you could have a solver that supports setting the objective only through `copy`. 

I like the basic fix in https://github.com/JuliaOpt/MathOptInterface.jl/pull/465. CachingOptimizer knows that `ConstraintSet` and `ConstraintFunction` are special in that there's a chance that they could be set through `copy!`. Maybe we should call `supports` when we see `MOI.UnsupportedAttribute` to confirm that we should try to rebuild the model?

**Comment by IssamT** [comment]
> Whatever change we adopt for constraints also has to apply for objectives, because you could have a solver that supports setting the objective only through copy.

Right.

A quick question: In the current situation, apart from Function and Set, will we have other attributes that can be given to the model without using `MOI.set!` and which are not part of `MOI.ListOfConstraintAttributesSet`?

**Comment by mlubin** [comment]
Nothing comes to mind. @blegat?
