### ISSUE TITLE
Rename supports

### ISSUE THREAD

**Issue by blegat** [JuliaOpt/MathOptInterface.jl#469]
There have been some discussion in https://github.com/JuliaOpt/MathOptInterface.jl/pull/468 about whether we should rename `copy`. The reason is that `supports` is about whether the element is supported, not whether some operation is supported so the less ambiguous way to define supports is "would it work if a model `src` containing this element is copied to the model".
Which naming do you prefer ? :

* `supports_constraint_via_copy` and `supports_via_copy` :+1: 
* `copy_supports_constraint` and `copy_supports` :heart: 
* `supports_constraint` and `supports` :tada:

**Comment by IssamT** [comment]
Does the vote *support* the multiple choices that one is fine with?

**Comment by blegat** [comment]
Yes :)

**Comment by odow** [comment]
The only problem with `NotAllowed` is that it doesn't say why it isn't allowed. I think it should reference copy in the name.

I like @mlubin's suggestion of `UnsupportedError` and `OnlySupportedViaCopyError` errors.

Of the three options, I prefer `supports_via_copy` :+1:

**Comment by mlubin** [comment]
I'm ready to move on and accept `NotAllowed` (a week of bikeshedding is enough). It's standard terminology, unlike "cannot", for explaining that an operation can't be performed in the current state of the object.

**Comment by mlubin** [comment]
Looks like we're not renaming for now.
