### ISSUE TITLE
Helper functions

### ISSUE THREAD

**Issue by joaquimg** [JuliaOpt/MathOptInterface.jl#47]
Some functions like converting Matrices to MOI VectorAffineFunction format might be very useful for users, for instance this sketch:
```julia
function triplets(A::SparseMatrixCSC, cols::Vector{MOI.VariableReference}, rows::Vector{I})
    @assert A.m == length(rows)
    @assert A.n == length(cols)
    colval = colval(A.colptr, length(A.rowval))
    return rows[A.rowval], cols[colval], A.nzvals    
end
function colval(colptr::Vector{I}, n::Integer)
    colval = zeros(I, n)
    c = 1
    for i in 1:length(colptr)-1
        for j in colptr[i]:(colptr[i+1]-1)
            colval[c] = I(i)
            c+=1
        end
    end
    return colval
end
```
Would it be good to have a MOIExtras.jl?
Maybe solver APIs have similar functions that could also go into MOIExtras.jl ...

**Comment by mlubin** [comment]
Aren't these two functions covered by `findnz` and `sparse`?

**Comment by mlubin** [comment]
Oh, I guess `SparseMatrixCSC` won't let you do variables as column indices.

**Comment by joaquimg** [comment]
yep, thats the problem

**Comment by blegat** [comment]
@joaquimg You are welcome to add it to https://github.com/JuliaOpt/MathOptInterfaceUtilities.jl :)

**Comment by joaquimg** [comment]
Can I close this? Creating https://github.com/JuliaOpt/MathOptInterfaceUtilities.jl is enough, right?

**Comment by blegat** [comment]
Yes, you can close it, we can reopen it in MOIU if we add to add these functions there.
