### ISSUE TITLE
Result attributes

### ISSUE THREAD

**Issue by blegat** [JuliaOpt/MathOptInterface.jl#480]
The caching and bridge optimizer need to distinguish two types of attributes when implementing `get`:

* Attributes for which the value of get is determined by the value that was set when copying the model.
* Attributes for which the value of get is determined by computation done during `optimize!`.

The distinction between these attributes is currently done using the `is_result_attribute` defined in MOIU.

The issue with this is that if someone create a new attribute, he needs to implement this method for this attribute and that is unexpected for a function defined in MOIU and not in MOI (see
https://github.com/JuliaOpt/MathOptInterface.jl/pull/479#discussion_r211470155). I see 2 solutions:

* Move the function to MOI as a mandatory function to implement
* Move the function to MOI and return `false` by default
* Move the function to MOI and return `true` by default
* Create `AbstractResultModelAttribute <: AbstractModelAttribute`, ...

What do you think ?

**Comment by mlubin** [comment]
There's also a related concept of attributes that are not listed in `ListOf...AttributesSet` that we should clarify at the same time.

**Comment by blegat** [comment]
I think the cleanest way would be to define new abstract types. What do you think of the following.

* `AbstractResultModelAttribute`/`AbstractResultConstraintAttribute`/`AbstractResultVariableAttribute`: Attributes that are modified by `MOI.optimize!`
* `AbstractCopiedModelAttribute`/`AbstractCopiedConstraintAttribute`/`AbstractCopiedVariableAttribute`: Attributes that are **explicitly** copied during `copy!`. These attributes can appear in `ListOf...Set`. `supports` should only be defined for these attributes.

Attributes that do not fall in these categories are `ListOf...`, `NumberOf...`, `ConstraintFunction` and `ConstraintSet`, ...

What do you think ?

**Comment by mlubin** [comment]
That's a lot of abstract types. What about a trait? For example, ``modified_by_optimize(::MOI.ResultCount) = Val{true}()`` (use `Val{true}()` for type stability).

**Comment by blegat** [comment]
Traits would work. So the names would be `is_set_by_optimize` and `is_copied` ?

**Comment by mlubin** [comment]
Who is responsible for copying the attributes? `is_copied` is a bit unclear given that `copy_to` can be implemented in multiple ways,

**Comment by blegat** [comment]
`can_be_copied` ?

**Comment by mlubin** [comment]
`copyable`?

**Comment by blegat** [comment]
`is_copyable` ? To be consistent with `is_valid`
