### ISSUE TITLE
What happens when deleting a variable in a constraint?

### ISSUE THREAD

**Issue by odow** [JuliaOpt/MathOptInterface.jl#511]
As [raised by Miles](https://github.com/JuliaOpt/JuMP.jl/pull/1445#discussion_r213150825), what should happen when the user tries to delete a variable that still exists in a constraint?

It seems like there are a few possible answers:
1. the variable gets deleted and the constraints are modified. This is easy for scalar terms, but less obvious for quadratic terms. Do they become linear?
    - [ ] todo: check what happens in Gurobi etc.
2. the solver throws and error and says delete constraints associated with the variable first
3. solver-specific -- some solvers allow, others will throw an error.

Thoughts?

**Comment by joaquimg** [comment]
I don't think its a nice optimization API if you need to delete or modify constraints explicitly when you delete a variable.
I don't know about quadratics, maybe thats why Xpress does not separates them. Also, Xpress has a method to identify constraints with quadratic terms, once all variables in quadratic terms for a constraint are deletes the constraint is identified as a linear constraint.

**Comment by blegat** [comment]
If one deletes a variable part of a VectorOfVariables constraint, it should be an error except when it deletes a vector of variables and all the variables of the VectorOfVariables constraint are deleted

**Comment by joaquimg** [comment]
> If one deletes a variable part of a VectorOfVariables constraint, it should be an error except when it deletes a vector of variables and all the variables of the VectorOfVariables constraint are deleted

this makes a lot of sense, but I am afraid that going for consistency might harm a lot the interface. Maybe we need a new kind of delete?

**Comment by blegat** [comment]
Like one `delete` that errors if constraints are still using the variable and one `delete_clean` that also sets the variable to zero in all functions ?

**Comment by joaquimg** [comment]
thats a possibility

**Comment by odow** [comment]
When Gurobi deletes a variable, it deletes the corresponding column from the linear A matrix, and deletes the row and column from any quadratic Q matrix. So if there are `x*y` cross-terms, these are deleted as well; they are not converted to linear terms.

Gist: https://gist.github.com/odow/8a4b4b529ae47c18b64b57feebd45a47

**Comment by odow** [comment]
There are so many edge-cases to consider. 
- What happens if I have `ObjectiveFunction{SingleVariable}` and then delete that variable? What type is the objective function?
- If I have a quadratic objective with `x^2`, and then I delete `x`, is the objective linear? Or quadratic with no terms? 
- I JuMP stores a copy of everything in a caching optimizer, does deleting a variable mean that it has to go through every constraint looking for terms with `x` in it?
- What happens if different solvers delete quadratic terms differently?

At first glance "delete a variable" seems like a well-defined operation. But once you dig in, it opens a big can of worms.

**Comment by mohamed82008** [comment]
> When Gurobi deletes a variable, it deletes the corresponding column from the linear A matrix, and deletes the row and column from any quadratic Q matrix. So if there are x*y cross-terms, these are deleted as well; they are not converted to linear terms.

I think this is the most intuitive thing to do because if I am writing a model with quadratic terms and linear terms in JuMP syntax for example, then I would iterate over all the indices of `x` an `y`, check a condition then add the term `a[i,j]*x[i]*y[j]` to the constraint if the condition is satisfied. So I think deleting a variable should be equivalent to skipping one of the indices for `x` or `y`.

> What happens if I have ObjectiveFunction{SingleVariable} and then delete that variable? What type is the objective function?

Error?

> If I have a quadratic objective with x^2, and then I delete x, is the objective linear? Or quadratic with no terms?

I think keeping it as quadratic makes sense to avoid changing types.

**Comment by joaquimg** [comment]
> What happens if I have ObjectiveFunction{SingleVariable} and then delete that variable? What type is the objective function?

Feasibility

> If I have a quadratic objective with x^2, and then I delete x, is the objective linear? Or quadratic with no terms?

Quadratic with no terms

> If JuMP stores a copy of everything in a caching optimizer, does deleting a variable mean that it has to go through every constraint looking for terms with x in it? (Edit: I think it does this.)

yes, caching optimizer should be updated

> What happens if different solvers delete quadratic terms differently?

I think we should see what Gurobi, CPLEX and Xpress do before deciding.
