### ISSUE TITLE
Slack and Unslack bridge

### ISSUE THREAD

**Issue by blegat** [JuliaOpt/MathOptInterface.jl#528]
- [x]  SlackBridge: Transforms a constraint `F`-in-`S` where `F` is AbstractFunction different from `SingleVariable` and `VectorOfVariables` and `S` is any set into a constraint `F`-in-`Zeros` and a constraint `SingleVariable` (or `VectorOfVariables`) in `S` (https://github.com/JuliaOpt/MathOptInterface.jl/pull/610).
- [x] VectorOfVariablesBridge (resp. SingleVariableBridge): Transforms a constraint `VectorOfVariables`-in-`AbstractVectorSet` (resp. `SingleVariable`-in-`AbstractScalarSet`) into `VectorAffineFunction`-in-`AbstractVectorSet` (resp. `ScalarAffineFunction`-in-`AbstractScalarSet`).

Not yet totally convinced by the names so any better idea would be appreciated :)

**Comment by joaquimg** [comment]
@blegat have you started working on it? I was planning to give it a try myself.

**Comment by blegat** [comment]
Not at all, feel free :)

**Comment by joaquimg** [comment]
My first idea was to create a single bridge for scalar and vector functions, but due to type instability it might be much harder to write a single bridge. So I decided to split and the scalar one would go like this:
```julia
struct ScalarSlackBridge{T, F<:MOI.AbstractScalarFunction, S<:MOI.AbstractScalarSet} <: AbstractBridge
    slack::MOI.VariableIndex
    slack_in_set::CI{MOI.SingleVariable, S}
    equality::CI{F, MOI.EqualTo{T}}
end
```
My first draft is here: https://github.com/JuliaOpt/MathOptInterface.jl/commit/fbb946d4e5196f618da5678e5b2ddfe7257e6831
Suggestions appreciated :)

**Comment by joaquimg** [comment]
I am, but I plan to finish the slack bridge this week only. My schedule would be to do the unslack before the end of january.
If you are in need go for it.

**Comment by joaquimg** [comment]
Now I am going for the second group

**Comment by blegat** [comment]
Unslack done in https://github.com/JuliaOpt/MathOptInterface.jl/pull/659
