### ISSUE TITLE
Objective function bridge

### ISSUE THREAD

**Issue by blegat** [JuliaOpt/MathOptInterface.jl#529]
It would be nice to have a bridge that transforms an unsupported objective into a SingleVariable objective with a LessThan (or GreaterThan depending on objective sense) constraint.
See https://github.com/JuliaOpt/SCS.jl/pull/111#issuecomment-425214874

**Comment by blegat** [comment]
It could also bridge SingleVariable to ScalarAffineFunction, it would resolve https://github.com/JuliaOpt/Cbc.jl/issues/96

**Comment by leethargo** [comment]
Nice, we have the same issue in [SCIP.jl](https://github.com/SCIP-Interfaces/SCIP.jl/issues/80#issuecomment-453662154).

**Comment by blegat** [comment]
The short term solution is simply converting it to `MOI.ScalarAffineFunction` like what is done in https://github.com/JuliaOpt/SCS.jl/pull/116. `MOI.ObjectiveFunctionType` is wrong though for SCS since it does not remember that it was set as `MOI.SingleVariable` but that is acceptable as a short term solution.

**Comment by arnavs** [comment]
I just wanted to follow up on this issue and see if there's been any movement. As it stands currently, my Mosek license is basically unusable in Julia, so it would be great to merge stuff even if it's a bit clunky.

**Comment by odow** [comment]
> As it stands currently, my Mosek license is basically unusable in Julia

It looks like you successfully followed the instructions here https://github.com/JuliaOpt/MosekTools.jl/issues/2? 

> so it would be great to merge stuff even if it's a bit clunky.

This isn't implemented yet. If you would like to have a go, we can point you in the right direction.

**Comment by arnavs** [comment]
Yeah, the issue with that workaround is that it only holds for problems with all positive eigenvalues, as @blegat points out. 

Yeah, would be happy to. If you could briefly describe what needs to be done, I'll give it a shot.

**Comment by odow** [comment]
> Yeah, the issue with that workaround is that it only holds for problems with all positive eigenvalues

Mosek is a convex solver. If the matrix isn't PSD (i.e., it has negative eigenvalues), Mosek can't solve it.

**Comment by arnavs** [comment]
Just to be clear, the problem we're discussing is a quadratic objective `z' L z + z' q` for some vectors `z, q`, and some matrix `L`, with (in my setup) zero or one negative eigenvalues. 

I thought I was able to solve this problem before, but maybe we used different parameters. Maybe I was hallucinating.
