### ISSUE TITLE
Decision: Interval sets with lower > upper

### ISSUE THREAD

**Issue by odow** [JuliaOpt/MathOptInterface.jl#532]
This came up in GLPK (see https://github.com/JuliaOpt/GLPK.jl/pull/81): what should we do if a user says add `x -in- Interval(1.0, -1.0)`?

- Do we throw an error at the creation of Interval?
- Or add the constraint, and return infeasible? If so, what about infeasibility certificates etc.

In the MPB world, a decision was made for GLPK to add the constraint and return infeasible (see https://github.com/JuliaOpt/GLPKMathProgInterface.jl/pull/34). This adds complexity to the wrapper as GLPK will throw an error on solve, so the wrapper has to check bounds prior to solve.

I'm in favor of throwing an error at the MOI level on the creation of Interval. 

TODO before closing:
- [ ] Add a test

**Comment by blegat** [comment]
I agree, there is no way to build an infeasibility ray anyway. For instance for 1 < x < -1 you need 1 for the lb and -1 for the ub. However the dual of a constraint can just be a scalar

**Comment by mlubin** [comment]
`InvalidModel` is a valid termination status to return if the solver looks at the data when trying to solve and decides that the input doesn't satisfy a required condition.

If we want to allow wrappers to throw an error on the `add_constraint` call, we need to standardize on an error type so that there's hope of handling this situation programmatically.

**Comment by odow** [comment]
The conclusion of https://github.com/JuliaOpt/GLPK.jl/pull/81 seems to be that the behaviour is solver-specific. Some solvers may support it and return infeasible, other solvers may throw an `InvalidModel` termination status.

**Comment by odow** [comment]
Closing since I don't think there is anything to do here. Its solver specific functionality.
