### ISSUE TITLE
Duplicate names

### ISSUE THREAD

**Issue by blegat** [JuliaOpt/MathOptInterface.jl#536]
We want to stop requiring models to error when a duplicate name is set, see https://github.com/JuliaOpt/MathOptInterface.jl/pull/535.
What should be the requirement now ?
Maybe we can require it to error when the user does `MOI.get(model, MOI.VariableIndex, name)` where two or more variables have the name `name` and if there is only one variable having the name `name` but some other names have duplicates then it might error or not, we leave the choice in the implementation (in model, it errors when building the dict: https://github.com/JuliaOpt/MathOptInterface.jl/pull/535)
What do you think ?

We should also decide whether a model is *allowed* to error on `MOI.set` even if it is not *required*

**Comment by mlubin** [comment]
We could say that it is "invalid" for any two variables or two constraints to have the same nonempty name and leave it up to the implementation on how to detect it and when to throw an error. Implementations could choose to throw an error on the `set` or on the `get` or at some other point. What we should write down is that there must be an error either on the `get` or before. To catch user errors, implementations aren't allowed to silently ignore the existence duplicate names like Gurobi does in their interface. 

We can't write generic tests for this behavior; models would have to write their own tests to make sure they're consistent with the rules.  It's not ideal, but we're constrained by the performance considerations.

**Comment by blegat** [comment]
> We can't write generic tests for this behavior

Why can't we write the test
```julia
@test_throws ErrorException begin
    MOI.set(model, MOI.VariableName(), x, "a")
    MOI.set(model, MOI.VariableName(), y, "a")
    MOI.get(model, MOI.VariableIndex(), "a")
end
```
solvers can throw an error in either the second or third line.

**Comment by mlubin** [comment]
```julia
@test_throws ErrorException begin
    MOI.set(model, MOI.VariableName(), x, "a")
    MOI.set(model, MOI.VariableName(), y, "a")
    MOI.get(model, MOI.VariableIndex(), "a")
end
```
We can try that.

**Comment by blegat** [comment]
Note for future reference, we have changed our mind and setting duplicate names is now valid. Only `get` throws an error, see https://github.com/JuliaOpt/MathOptInterface.jl/issues/548
