### ISSUE TITLE
logdet cone definition is wrong (needs perspective variable)

### ISSUE THREAD

**Issue by chriscoey** [JuliaOpt/MathOptInterface.jl#546]
the logdet function is not homogeneous, hence its hypograph (t,X) : t <= logdet(X) is convex but not conic. the "logdet cone" is therefore a misnomer. we should redefine the logdet cone as (x, y, Z) : x <= y*logdet(Z/y).

I'm happy to go through and do this.

**Comment by blegat** [comment]
I am in favor of this change, it is indeed not a cone at the moment. It seems that the bridge can be adapted without much trouble, we just need to replace the `one(T)` here:
https://github.com/JuliaOpt/MathOptInterface.jl/blob/9df0ad82df86cd54c9bc03d389be6d0842f9cb4c/src/Bridges/detbridge.jl#L99
by the perspective `y`.
