### ISSUE TITLE
discussion of overlapping variable bounds

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/MathOptInterface.jl#56]
Discuss in the manual that it's reasonable for solvers to reject multiple variable-wise lower bounds on the same variable. See, e.g., https://github.com/JuliaOpt/MathOptInterface.jl/pull/53.

**Comment by IssamT** [comment]
And he do we do overriding of bounds? deleting and adding new "bound" constraint ?

**Comment by mlubin** [comment]
Yes, delete and add, or modify the set. This way the solver doesn't need to store a "stack" of bounds for a single variable.
