### ISSUE TITLE
add rotated second-order cone

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/MathOptInterface.jl#57]

**Comment by joaquimg** [comment]
I can do it

**Comment by joaquimg** [comment]
the rotated SOC is always a variablewise constraint?

Or should it be in this table somehow?

| Mathematical Constraint                                       | MOI Function                 | MOI Set                            |
|---------------------------------------------------------------|------------------------------|------------------------------------|
| ``\lVert Ax + b\rVert_2 \le c^Tx + d``                        | `VectorAffineFunction`       | `SecondOrderCone`                  |

**Comment by mlubin** [comment]
No, it's not always variablewise.

**Comment by mlubin** [comment]
Closed by #59
