### ISSUE TITLE
"NotSolved" TerminationStatus (or equivalent)

### ISSUE THREAD

**Issue by odow** [JuliaOpt/MathOptInterface.jl#572]
As raised by https://github.com/JuliaOpt/JuMP.jl/issues/1618, what should optimizers return as `TerminationStatus` when the problem hasn't been solved yet?

```julia
model = Model()
JuMP.termination_status(model)
```

Here is the list of current `TerminationStatus`:
https://github.com/JuliaOpt/MathOptInterface.jl/blob/81c115594f6cc0dae3d288d69ffa428eadc0f5b7/src/attributes.jl#L722

**Comment by blegat** [comment]
`NotSolved` is a good name

**Comment by mlubin** [comment]
NotSolved SGTM. This is consistent with the NoSolution status.

**Comment by mlubin** [comment]
Actually, NotSolved could be interpreted as implying that a solved was attempted. Maybe OptimizeNotCalled?

**Comment by odow** [comment]
`OpitimizeNotCalled` seems fine.

**Comment by blegat** [comment]
`OpitimizeNotCalled` is even better
