### ISSUE TITLE
How will LP solvers know bound constraint type

### ISSUE THREAD

**Issue by IssamT** [JuliaOpt/MathOptInterface.jl#58]
A bound constraint can be given either as a constraint or as a bound. With the current MOI interface are we able to distinguish those?

**Comment by joaquimg** [comment]
ScalarAffineFunction in set is a constraint
ScalarVariablewiseFunction in a set is a bound

**Comment by mlubin** [comment]
You should think of the variablewise constraints as what will be passed as variable bounds to the solver and the affine constraint as a normal linear constraints

**Comment by IssamT** [comment]
I agree. that makes sense. Is this already in the documentation?

**Comment by mlubin** [comment]
It is supposed to be covered already in the table on linear constraints but it may not be very clear.

**Comment by IssamT** [comment]
I wanted to add a line in the solver implementation section, to clarify that even if ScalarAffineFunction has only one term it should not be considered as a bound.

**Comment by mlubin** [comment]
We should add a note on the intended implementation in the last section.
