### ISSUE TITLE
docs seem to use incorrect formulae for triangle -> square index conversion

### ISSUE THREAD

**Issue by chriscoey** [JuliaOpt/MathOptInterface.jl#588]
https://github.com/JuliaOpt/MathOptInterface.jl/blob/b2463a52f91cb8a6e06478b22dac8f3bd0340cd0/src/sets.jl#L230

on Julia master:
```
julia> # get (i,j) matrix indices (lower triangle, row major) for kth term in vector
       function vectomatidx(k)
           i = isqrt(2*k)
           j = k - div((i-1)*i, 2)
           return (i,j)
       end
vectomatidx (generic function with 1 method)

julia> vectomatidx.(1:6)
6-element Array{Tuple{Int64,Int64},1}:
 (1, 1)
 (2, 1)
 (2, 2)
 (2, 3)
 (3, 2)
 (3, 3)
```
the fourth (i,j) indices are incorrect: they should be (3, 1) not (2, 3)

**Comment by chriscoey** [comment]
I used this method: https://math.stackexchange.com/questions/813576/transform-a-symmetric-matrix-to-a-vector-and-multiplicate
and it seems to work:
```
julia> function vectomatidx(k)
           i = floor(Int, (1+sqrt(8*k-7))/2)
           j = k - div(i*(i-1), 2)
           return (i,j)
       end
vectomatidx (generic function with 1 method)

julia> vectomatidx.(1:6)
6-element Array{Tuple{Int64,Int64},1}:
 (1, 1)
 (2, 1)
 (2, 2)
 (3, 1)
 (3, 2)
 (3, 3)

julia> vectomatidx.(1:10)
10-element Array{Tuple{Int64,Int64},1}:
 (1, 1)
 (2, 1)
 (2, 2)
 (3, 1)
 (3, 2)
 (3, 3)
 (4, 1)
 (4, 2)
 (4, 3)
 (4, 4)
```

**Comment by blegat** [comment]
I agree, I don't remember where the `isqrt(2k)` comes from but it is incorrect. The method in stackexchange seems correct.

**Comment by blegat** [comment]
Normally no wrapper were using this formula but were rather relying on the mapping `(i, j) -> k`, e.g.
https://github.com/JuliaOpt/MathOptInterfaceMosek.jl/blob/5652c097f3f7bcf1fd99085ae4865aa96295cb14/src/constraint.jl#L109-L111
or even were just iterating over the three indices without the need for any explicit mapping:
https://github.com/JuliaOpt/MathOptInterface.jl/blob/a481d6eb6842cc33b22962b2bbac5c551b38ca6f/src/Bridges/squarepsdbridge.jl#L83-L86
