### ISSUE TITLE
Rename variablewise functions

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/MathOptInterface.jl#60]
The name "variablewise function" is a holdover from variablewise constraint, which made a bit more sense.
To replace `ScalarVariablewiseFunction` and `VectorVariablewiseFunction`, what about  ``ScalarComponentProjection`` and ``VectorComponentProjection``?

Let the bikeshedding begin. @blegat @joehuchette @chriscoey @odow @joaquimg @IssamT 

Thanks to @edljk for pointing this out.

**Comment by IssamT** [comment]
or `ScalarIdentityFunction` and `VectorIdentityFunction` ?

**Comment by mlubin** [comment]
The issue is that these are not identity functions by any usual definition of identity, except when all variables appear in the map. They *are* coordinate-wise projections by any usual definition.

**Comment by blegat** [comment]
Maybe `ScalarProjectionFunction` and `VectorProjectionFunction` to keep the `Function` suffix ?

**Comment by mlubin** [comment]
We could say `ScalarProjection` and `VectorProjection` to keep it shorter.

**Comment by mlubin** [comment]
Although in the future I can imagine someone wanting to add other kinds of projections.

**Comment by odow** [comment]
What's wrong with `Variablewise`?

I'd almost prefer
```
ScalarFunction(Variable, args... )
ScalarFunction(Affine, args... )
ScalarFunction(Quadratic, args... )

addconstraint!(m, ScalarFunction(Affine, x, [1.0,1.0], 0.0), LessThan(5.0))
```
or
```
VectorFunction{Variable}(args... )
VectorFunction{Affine}(args... )
VectorFunction{Quadratic}(args... )
```
or just `ScalarFunction` and `VectorFunction` and the type is inferred from the number of arguments.

**Comment by mlubin** [comment]
> What's wrong with `Variablewise`?

Affine and quadratic functions are well-defined and widely used concepts. Variablewise is not. Why not just use the mathematically correct and clear name for the function?

It could be useful to formalize the scalar/vector concept since it seems like we've converged to definitions of sets that are exclusively scalar or vector sets. What are the `Variable`, `Affine`, and `Quadratic` objects though? Wouldn't it be confusing to have a type called `Variable` which is just a placeholder for dispatch and not an actual variable?

> or just `ScalarFunction` and `VectorFunction` and the type is inferred from the number of arguments.

That's not extensible, so I'd downvote that.

**Comment by mlubin** [comment]
Another idea: ``SingleVariable`` and ``VectorOfVariables``.
These seem more self-explanatory than ``ScalarVariablewiseFunction`` and ``VectorVariablewiseFunction``. The description "single" is meant to evoke the idea that you're extracting one variable out of all of the variables in the model:
```julia
addconstraint!(m, SingleVariable(x[1]), LessThan(10.0))
addconstraint!(m, VectorOfVariables(x[1:5]), AllDifferent(5)) # thinking ahead...
```
It wouldn't be too crazy to have a fallback like:
```julia
addconstraint!(m, v::VariableReference, s) = addconstraint!(m, SingleVariable(v), s)
addconstraint!(m, v::Vector{VariableReference}, s) = addconstraint!(m, VectorOfVariables(v), s)
```
but that's a mostly separate discussion.

**Comment by joaquimg** [comment]
This is my favorite among all the other suggestions. 
And I liked the fallback

**Comment by blegat** [comment]
I am ok with either `ScalarProjection`/`VectorProjection` or `SingleVariable`/`VectorOfVariable` and I upvote the callback :)
