### ISSUE TITLE
Missing AlmostDualInfeasible

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/MathOptInterface.jl#601]
For ECOS (https://www.embotech.com/ECOS/How-to-use/C-API):

   

12 | Certificate of dual infeasibility found subject to reduced tolerances | ECOS_DINF + ECOS_INACC_OFFSET
-- | -- | --

**Comment by blegat** [comment]
It also corresponds to SCS `-6 SCS_UNBOUNDED_INACCURATE`
