### ISSUE TITLE
solver-independent options

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/MathOptInterface.jl#61]
... haven't been ported to MOI yet. Are they `Solver` attributes? `SolverInstance` attributes? Both? Something else?

**Comment by odow** [comment]
I think the more weird problem classes MOI supports, the less solver-independent options make sense. Time limit and a print verbosity both seem algorithm/solver/problem independent though, so maybe it should just be those two.

**Comment by odow** [comment]
The other day @mlubin and I discussed the idea that tolerances and other options should be a component of any model instance with floating point arithmetic. (The discussion was based around what features to include in https://github.com/odow/MathOptFormat.jl)

For example, a natural tolerance that is widely understood (and necessary) is the integrality tolerance (i.e. in [Gurobi](http://www.gurobi.com/documentation/7.5/refman/intfeastol.html#parameter:IntFeasTol))
```julia
struct IntegerFeasibilityTolerance <: AbstractConstraintAttribute end
c = addconstraint!(m, x, Integer())
setattribute!(m, IntegerFeasibilityTolerance(), c, 1e-6)
```
We may also want to include [primal feasibility](http://www.gurobi.com/documentation/7.5/refman/feasibilitytol.html#parameter:FeasibilityTol) and [dual feasibility](http://www.gurobi.com/documentation/7.5/refman/optimalitytol.html#parameter:OptimalityTol) tolerances:
```julia
struct PrimalFeasibilityTolerance <: AbstractConstraintAttribute end
struct DualFeasibilityTolerance <: AbstractConstraintAttribute end
c = addconstraint!(m, ScalarAffineFunction([x], [1.0]), LessThan(1.0))
setattribute!(m, PrimalFeasibilityTolerance(), c, 1e-6)
setattribute!(m, DualFeasibilityTolerance(), c, 1e-6)
```

http://www.gurobi.com/documentation/7.5/refman/feasibilitytol.html#parameter:FeasibilityTol

**Comment by odow** [comment]
We're going to to hold off on tolerances for now. The two to push forward with are silent and time-limit.

**Comment by mlubin** [comment]
Basic solver-independent options like `Silent` are already implemented.
