### ISSUE TITLE
`VectorOfVariables` should allow the same variable twice?

### ISSUE THREAD

**Issue by joaquimg** [JuliaOpt/MathOptInterface.jl#611]
Should this be allowed?

```julia
x = add_variable(model)
vov = VectorOfVariables([x, x, x])
add_constraint(model, vov, SecondOrderCone(3))
```

**Comment by odow** [comment]
I don't see why not, but I presume that this could lead to invalid constraints. What is an SOS1 constraint with duplicate variables?

**Comment by chriscoey** [comment]
it should definitely be allowed for convex optimization modeling (and is useful at times).

**Comment by odow** [comment]
Closing since the answer is yes.
