### ISSUE TITLE
Refactor MOI._constant and MOIU.getconstant

### ISSUE THREAD

**Issue by blegat** [JuliaOpt/MathOptInterface.jl#618]
Create good names consistent with the [JuMP style guide](http://www.juliaopt.org/JuMP.jl/v0.19.0/style/)

**Comment by matbesancon** [comment]
@blegat there is `__constant` in Bridge, should this be merged too? It would require moving functions around, otherwise this would be type piracy from MOIU

**Comment by blegat** [comment]
Yes, I mentioned in https://github.com/JuliaOpt/MathOptInterface.jl/pull/723#issuecomment-488594980 (I didn't see your comment when writing this one), we can merge it with `__constant` and move the implementations to MOI
