### ISSUE TITLE
Read/write from/to file should be IO not filenames

### ISSUE THREAD

**Issue by odow** [JuliaOpt/MathOptInterface.jl#633]
Currently we have
https://github.com/JuliaOpt/MathOptInterface.jl/blob/b63ab44e22cd23d86296aff7f465bb95f32a85e2/src/MathOptInterface.jl#L43

but it would be better change this to `read_from_file(model, io::IO)` and to have a fallback
```julia
function read_from_file(model::ModelLike, io::IO)
    error("read_from_file not implemented for model of type $(typeof(model))")
end

function read_from_file(model::ModelLike, filename::String)
    open(filename, "r") do io
        read_from_file(model, io)
    end
end
```
The motivation is to enable MathOptFormat to support GZipped files https://github.com/odow/MathOptFormat.jl/issues/39. cc @chriscoey

**Comment by chriscoey** [comment]
we may also need to change the docstring at https://github.com/JuliaOpt/MathOptInterface.jl/blob/b63ab44e22cd23d86296aff7f465bb95f32a85e2/src/MathOptInterface.jl#L55
because some file formats (such as CBF) do not have variable names, only indices

@odow I would like to get this in soon, do you want to submit a PR or should I?

**Comment by chriscoey** [comment]
should it be `read_from_file(model::ModelLike, io::IO)` or `read_from_file(io::IO, model::ModelLike)` (and same for `write_to_file`)? in MOF.jl we have `Base.show(io::IO, ::Model)`

**Comment by odow** [comment]
I'm in New York until Monday night, so I won't be making progress on this in the near future. 

Given the MOI definitions are just docstrings, let's implement the most convenient functions in MOF and update the docstrings later. I think we're the only ones playing with this anyway.

I don't mind order of arguments so long as they are consistent. Model then io/file makes most sense. Reads as: read model from file, and: write model to file.

**Comment by chriscoey** [comment]
@odow @mlubin any recent thoughts on this and #635?

**Comment by odow** [comment]
I feel like we need 
```Julia
function read_from_file(model::ModelLike, io::IO; filetype)
end
```

Whether `filetype` is a [MIME string](https://github.com/JuliaOpt/MathOptInterface.jl/pull/635#discussion_r251182918) or a type, I'm not sure.

But it seems that the MIME's are more brittle. I would prefer that MOI defined:
```Julia
abstract type AbstractFileFormat end
```
so you could go
```Julia
read_from_file(model, io, file_type = MathOptFormat.MPSFile())
```
