### ISSUE TITLE
Different results between equivalent RotatedSecondOrderCone and SecondOrderCone constraints

### ISSUE THREAD

**Issue by pseudocubic** [JuliaOpt/MathOptInterface.jl#651]
There seems to be a difference in my results when using (what I think should be) equivalent formulations of a complex product constraint with `SecondOrderCone` vs `RotatedSecondOrderCone`. I have posted here because these functions in JuMP are documented as being simply shortcuts to these functions in MOI. I believe that 
```julia
@constraint(model, wr^2 + wi^2 <= w[1]*w[2]
@constraint(model, [w[1]+w[2], w[1]-w[2], 2wr, 2wi] in SecondOrderCone())
@constraint(model, [w[1], w[2], wr, wi] in RotatedSecondOrderCone())
```
should all result in the same objective values for my problem, but the `RotatedSecondOrderCone` construction gives me a significantly different answer. Below is a script with a the model I have used to test this:

```julia
using JuMP, SCS, Ipopt

function socwr_test(con="default")
    if con == "default"
        ipopt_solver = with_optimizer(Ipopt.Optimizer, print_level=0)
        model = JuMP.Model(ipopt_solver)
    else
        scs_solver = with_optimizer(SCS.Optimizer, verbose=0)
        model = JuMP.Model(scs_solver)
    end

    # voltage
    @variable(model,  0.9 <= w[i=1:2] <= 1.1)
    @variable(model,  0.5 <= wr <= 1.2)
    @variable(model, -1.1 <= wi <= 1.1)

    # generator
    @variable(model,  0 <= pg <= 10)
    @variable(model, -1 <= qg <= 1)

    # branch flow
    @variable(model, p[i=1:2] <= 25)
    @variable(model, q[i=1:2] <= 25)

    # objective
    @objective(model, Min, 1000 * pg)

    # voltage constraints
    if con == "default"
        @constraint(model, wr^2 + wi^2 <= w[1]*w[2])
    elseif con == "soc"
        @constraint(model, [w[1]+w[2], w[1]-w[2], 2wr, 2wi] in SecondOrderCone())
    elseif con == "rsoc"
        @constraint(model, [w[1], w[2], wr, wi] in RotatedSecondOrderCone())
    end

    # power constraints
    @constraint(model, p[1] == -1.0)
    @constraint(model, q[1] == -0.5)
    @constraint(model, p[2] - pg == 0)
    @constraint(model, q[2] - qg == 0)
    @constraint(model, p[1] -  4w[2] +  4wr - 20wi == 0)
    @constraint(model, q[1] - 20w[2] + 20wr +  4wi == 0)
    @constraint(model, p[2] -  4w[1] +  4wr + 20wi == 0)
    @constraint(model, q[2] - 20w[1] + 20wr -  4wi == 0)


    JuMP.optimize!(model)

    return JuMP.objective_value(model)
end

d_obj = socwr_test()
soc_obj = socwr_test("soc")
rsoc_obj = socwr_test("rsoc")

println("Default:                $d_obj")
println("SecondOrderCone:        $soc_obj")
println("RotatedSecondOrderCone: $rsoc_obj")
println()
println("DEF-SOC Diff:    $(abs(d_obj - soc_obj))")
println("DEF-ROTSOC Diff: $(abs(d_obj - rsoc_obj))")
println("SOC-ROTSOC Diff: $(abs(soc_obj - rsoc_obj))")
```

This gives the following results:
```
Default:                1011.6716737349649
SecondOrderCone:        1011.6769050004009
RotatedSecondOrderCone: 699.9947553463844

DEF-SOC Diff:    0.00523126543600938
DEF-ROTSOC Diff: 311.6769183885805
SOC-ROTSOC Diff: 311.6821496540165
```

As you can see, the difference between using the `SecondOrderCone` and `RotatedSecondOrderCone` constraints is quite substantial compared to the original constraint, whose difference is negligible considering the usage of a different solver.

Is my understanding of these different constructions correct and this is a bug, or have I constructed the `RotatedSecondOrderCone` constraint wrong?

MacOS@10.14.2, Julia@1.1.0, JuMP@master, MOI@0.8.1, Ipopt@0.5.2, SCS@0.5.1

**Comment by blegat** [comment]
These are equivalent
```julia
@constraint(model, wr^2 + wi^2 <= 2w[1]*w[2]
@constraint(model, [w[1], w[2], wr, wi] in RotatedSecondOrderCone())
```
You are missing a 2 in the rhs of the first constraibt

**Comment by pseudocubic** [comment]
CC @ccoffrin

Ah, this would mean that for our case where we are attempting to make the constraint in JuMP v0.19  equivalent to the pre-existing one (`norm([w[1]-w[2],2c,2d]) <= w[1]+w[2]`), we should do:
```
@constraint(model, [w[1]/sqrt(2), w[2]/sqrt(2), wr, wi] in RotatedSecondOrderCone())
```
which results in
```
Default:                1011.6716737349649
SecondOrderCone:        1011.6769050004009
RotatedSecondOrderCone: 1011.6751488693751

DEF-SOC Diff:    0.00523126543600938
DEF-ROTSOC Diff: 0.0034751344102232906
SOC-ROTSOC Diff: 0.0017561310257860896
```

Thanks, this solves my problem!

**Comment by ccoffrin** [comment]
@blegat, this does not match the documentation.  

http://www.juliaopt.org/MathOptInterface.jl/stable/apireference/#MathOptInterface.RotatedSecondOrderCone

Also the variable is inverted from the SOC case, which for me is quite confusing.

**Comment by mlubin** [comment]
The 2 factor is in the documentation, what doesn't match? Which variable is inverted?

**Comment by ccoffrin** [comment]
The docs indicate the variable ordering `(t,u,x)`, as per this thread it is `(x,t,u)`.  In the SOC case it is `(t,x)`.

**Comment by mlubin** [comment]
That may have been a typo in @blegat's comment.

**Comment by ccoffrin** [comment]
aaa, Ok.  So where is the `sqrt(2)` come from in David's example?
```
@constraint(model, [w[1]/sqrt(2), w[2]/sqrt(2), wr, wi] in RotatedSecondOrderCone())
```

**Comment by mlubin** [comment]
```julia
@constraint(model, wr^2 + wi^2 <= w[1]*w[2])
```
is equivalent to
```julia
@constraint(model, [w[1]/sqrt(2), w[2]/sqrt(2), wr, wi] in RotatedSecondOrderCone())
```
or
```julia
@constraint(model, [w[1]/2, w[2], wr, wi] in RotatedSecondOrderCone())
```
or
```julia
@constraint(model, [w[1], w[2]/2, wr, wi] in RotatedSecondOrderCone())
```
The sqrt(2) version is more canonical.

**Comment by ccoffrin** [comment]
Aaaaaa, ok.  I get it.  Why does the RSOC set include a factor of two in it, is that a canonical form?

**Comment by mlubin** [comment]
With the factor of 2 the cone is self dual like SOC. This is much more convenient for any algorithms that use conic duality.

**Comment by ccoffrin** [comment]
Nice!  Thanks for helping us figure this out, been chasing that bug for a
couple of weeks now.
