### ISSUE TITLE
`VariableBasisStatus` and `ConstraintBasisStatus` not supported

### ISSUE THREAD

**Issue by EdvinAblad** [JuliaOpt/MathOptInterface.jl#655]
While testing JuMP 0.19 beta2 I found that non of the solvers I tested (Clp, GLPK, Gurobi) supported the
`MOI.get(model, MOI.ConstraintBasisStatus(), index)` or `MOI.get(model, MOI.VariableBasisStatus(), index)`
where model is backend of the JuMP model created by the with_optimizer and no additional input. 
The model was a LP model.

I search the JuliaOpt Repo and found `ConstraintBasisStatus` mentioned only in three places: in attributes.jl, bridge.jl, and in apireference.md (all in the MOI project). 

To me this seems like no solver supports these functions: are they obsolete? or are there plans to implement them? 
(For Clp at least the corresponding functions exists in MathProgBase interface)

**Comment by mlubin** [comment]
These are not implemented yet, and I don't consider them blocking for the 0.19 release. It's up for grabs by whoever needs this functionality. Given the existing MPB examples, it's probably not hard to implement the MOI versions for solvers of interest.

**Comment by blegat** [comment]
Closing as it's now implemented in at least Clp, GLPK and Gurobi which are mentioned in the first comment.
