### ISSUE TITLE
Drop Julia v0.6 and Julia v0.7

### ISSUE THREAD

**Issue by blegat** [JuliaOpt/MathOptInterface.jl#661]
See https://discourse.julialang.org/t/julia-0-6-and-0-7-are-now-officially-unmaintained/20449/2
Dropping a Julia release cannot be done in a patch release so I assign it to the v0.9 milestone.

- [x] Julia v0.6 https://github.com/JuliaOpt/MathOptInterface.jl/pull/714
- [ ] Julia v0.7 https://github.com/JuliaOpt/MathOptInterface.jl/pull/717

**Comment by matbesancon** [comment]
Fixed in #714

**Comment by blegat** [comment]
#714 only drops Julia v0.6. Any reason to keep Julia v0.7 ?

**Comment by matbesancon** [comment]
people still upgrading and not moving "brutally" from 0.6 to 1.0? But you're right we could remove it

**Comment by blegat** [comment]
Let's divide this issue in two and only drop Julia v0.6 for now

**Comment by matbesancon** [comment]
agreed
