### ISSUE TITLE
Make LogLevel a required solver option

### ISSUE THREAD

**Issue by ndinsmore** [JuliaOpt/MathOptInterface.jl#663]
Across the Julia ecosystem LogLevel is fairly standard as the verbosity identifying option. 

By making this part of the interface it would remove a lot of the difficulty in controlling the output to STDOUT.

**Comment by odow** [comment]
We previously had two solver-independent parameters:
`silent` and `time_limit`
https://mathprogbasejl.readthedocs.io/en/latest/solverinterface.html?highlight=timelimit#setparameters!

See also https://github.com/JuliaOpt/MathOptInterface.jl/issues/61

**Comment by blegat** [comment]
> Across the Julia ecosystem LogLevel is fairly standard as the verbosity identifying option.

What are the packages sharing the LogLevel convention ? What would be the difference between LogLevel 1 and 2 ?
