### ISSUE TITLE
Missing / for quadratic functions

### ISSUE THREAD

**Issue by blegat** [JuliaOpt/MathOptInterface.jl#672]
### What is the issue

The method `operate(::typeof(/), ::Type{T}, ::MOI.ScalarQuadraticFunction{T}, ::T)` is missing.

```julia
julia> using MathOptInterface

julia> const MOI = MathOptInterface
MathOptInterface

julia> v = MOI.SingleVariable(MOI.VariableIndex(1))
MathOptInterface.SingleVariable(MathOptInterface.VariableIndex(1))

julia> quad = 2.0v * v
MathOptInterface.ScalarQuadraticFunction{Float64}(MathOptInterface.ScalarAffineTerm{Float64}[ScalarAffineTerm{Float64}(0.0, VariableIndex(1))], MathOptInterface.ScalarQuadraticTerm{Float64}[ScalarQuadraticTerm{Float64}(2.0, VariableIndex(1), VariableIndex(1))], 0.0)

julia> quad / 2.0
ERROR: MethodError: no method matching operate(::typeof(/), ::Type{Float64}, ::MathOptInterface.ScalarQuadraticFunction{Float64}, ::Float64)
Closest candidates are:
  operate(::typeof(+), ::Type{T}, ::Any, ::Any, ::Any, ::Any...) where T at /home/blegat/.julia/dev/MathOptInterface/src/Utilities/functions.jl:799
  operate(::typeof(/), ::Type{T}, ::MathOptInterface.SingleVariable, ::T) where T at /home/blegat/.julia/dev/MathOptInterface/src/Utilities/functions.jl:1227
  operate(::typeof(/), ::Type{T}, ::MathOptInterface.ScalarAffineFunction{T}, ::T) where T at /home/blegat/.julia/dev/MathOptInterface/src/Utilities/functions.jl:1240
  ...
Stacktrace:
 [1] /(::MathOptInterface.ScalarQuadraticFunction{Float64}, ::Float64) at /home/blegat/.julia/dev/MathOptInterface/src/Utilities/functions.jl:1247
 [2] top-level scope at none:0
```

### Steps to solve the issue

1. Implement the method getting inspiration from
 https://github.com/JuliaOpt/MathOptInterface.jl/blob/1bdae588867d2c6a88485c94cba9e29ca6e76fbb/src/Utilities/functions.jl#L1232-L1241
2. Add tests in `test/Utilities/functions.jl`

**Comment by Peiffap** [comment]
If the issue isn't urgent, I'd like to have a look at this in a couple weeks, but feel free to give it to someone else if they can provide a solution in a shorter delay!

**Comment by Peiffap** [comment]
> 1. Implement the method getting inspiration from `operate(::typeof(/), ::Type{T}, ::MOI.ScalarQuadraticFunction{T}, ::T)`

This doesn't seem to be the right function, which one did you mean to write?

**Comment by blegat** [comment]
> > 1. Implement the method getting inspiration from `operate(::typeof(/), ::Type{T}, ::MOI.ScalarQuadraticFunction{T}, ::T)`
> 
> This doesn't seem to be the right function, which one did you mean to write?

Indeed, I have corrected it
