### ISSUE TITLE
Solver wrappers tracker

### ISSUE THREAD

**Issue by joaquimg** [JuliaOpt/MathOptInterface.jl#70]
List of LP and conic solver wrappers to be implemented.
We can mark whoever is currently working on it and which ones are basically done.
 - [ ] CDD (@blegat)
 - [x] Clp (@IssamT)
 - [x] Cbc 
 - [x] GLPK (@joaquimg)
 - [x] CSDP (@blegat)
 - [x] ECOS (@blegat)
 - [x] SCS (@blegat)
 - [x] SDPA (@blegat)
 - [x] CPLEX (@odow)
 - [x] Gurobi (@joaquimg)
 - [x] FICO Xpress (@joaquimg)
 - [x] Mosek (@ulfworsoe)
 - [ ] SCIP (@joaquimg)

**Comment by joaquimg** [comment]
Do you agree with that?
@blegat should I mark CSDP and SDPA as done?

**Comment by joaquimg** [comment]
I can do Gurobi also, it is pretty similar to Xpress

**Comment by mlubin** [comment]
This is a good place to keep track of progress and who's working on what.

I'd also mention that this is a good time to look at the low-level wrappers themselves, don't feel like you can only touch the MOI code. A lot of these wrappers were written a long time ago and don't necessarily have good documentation or follow the latest Julia conventions. Please take some time to consider if it would be useful to reorganize the low-level wrapper before or while writing the MOI wrapper.

**Comment by mlubin** [comment]
Any if any part of the implementation is unclear, open an issue here so we can document it! Hopefully the guide on "how to write a solver wrapper" can be easily compiled from the experience with these wrappers.

**Comment by odow** [comment]
I can do CPLEX

**Comment by odow** [comment]
A question on the low-level wrappers: should these support a full range of low-level features (i.e. adding variables with bounds at the same time), or just the MOI features (add a variable, and a function to set bounds). Consider that CPLEX has [`addcols`](https://www.ibm.com/support/knowledgecenter/SSSA5P_12.7.1/ilog.odms.cplex.help/refcallablelibrary/cpxapi/addcols.html) and [`newcols`](https://www.ibm.com/support/knowledgecenter/en/SSSA5P_12.7.1/ilog.odms.cplex.help/refcallablelibrary/cpxapi/newcols.html) for adding new variables (with an without constraint coefficents), as well as six Julia methods for adding variables depending on the type of input arguments.

I'm kind of in favour of restricting the functionality of the low-level wrappers because it will encourage people to go through MOI and make it simpler to maintain.

**Comment by joaquimg** [comment]
I was thinking about something similar, maybe having the C api .h file converted just to eliminate tedious ccalling and then just do MOI.
I think it is similar to what is done in GLPK.

**Comment by blegat** [comment]
@joaquimg CSDP is passing the `contconic` tests but not the `contlinear` tests yet. `SDPA` has not been adapted yet but it will be very quick since all the hard work is done by SOI :)

**Comment by mlubin** [comment]
@odow a smart MOI wrapper might decide to call ``addcols`` for column generation after collecting the new variables and coefficients together.

**Comment by mlubin** [comment]
> Have anybody tried to use any .h to .jl converter such as the one in Clang.jl

We tried a long time ago for SCIP and it wasn't successful because the SCIP API was too complicated.

**Comment by blegat** [comment]
@joaquimg never tried it but I am planning to give it a try for DSDP

**Comment by blegat** [comment]
DSDP is passing all `contlinear` and `contconic` tests so I have marked it as done :)

**Comment by blegat** [comment]
SDPA too now :)

**Comment by joaquimg** [comment]
Xpress is passing linear1test

**Comment by joaquimg** [comment]
My plan is finish intlinear soon and go to gurobi

**Comment by joaquimg** [comment]
I finished Xpress intlinear, I will move to Gurobi soon. 
@odow would you like to comment on what I have done in Xpress before I move to gurobi?
@mlubin would Gurobi help you with JuMP integer tests?

**Comment by mlubin** [comment]
@joaquimg I'm just targeting LP this week, but if we have a MIP solver working I may have time to try it out.

**Comment by odow** [comment]
CPLEX is now passing tests 1 to 6.
https://github.com/JuliaOpt/CPLEX.jl/pull/139

**Comment by odow** [comment]
CPLEX is now passing all contlinear, intlinear, and contquadratic tests in this branch https://github.com/JuliaOpt/MathOptInterface.jl/pull/103 with the exception of linear7test and qpp2test (vector valued functions).

**Comment by leethargo** [comment]
I'm sure this has been discussed elsewhere, but: Is the idea that the MOI wrapper is implemented in the same repo as the existing MPB wrapper, and that the latter is removed in the processed?

**Comment by ulfworsoe** [comment]
MOSEK is now passing linear, conic and integer tests (minus SOS tests). I have not implemented quadratic objective or constraints. I have also disabled `MathProgBase` support.

**Comment by joaquimg** [comment]
> CPLEX is now passing all contlinear, intlinear, and contquadratic tests in this PR #103 with the exception of linear7test and qpp2test (vector valued functions).

Same for Xpress using LinQuadOptInterface

**Comment by joaquimg** [comment]
I am tagging Xpress.jl v0.5.0 now and it contains the basic functions to support [XpressMathOptInterface](https://github.com/joaquimg/XpressMathOptInterface.jl) which depends on [LinQuadOptInterface](https://github.com/joaquimg/LinQuadOptInterface.jl).

@mlubin I'd like to transfer these two to JuliaOpt.

I will start working on [GurobiMathOptInterface](https://github.com/joaquimg/GurobiMathOptInterface.jl)

@odow should I also create `CPLEXMathOptInterface`?

**Comment by mlubin** [comment]
@joaquimg, you have permission to transfer those two repos.

Does the Xpress v0.5 release have any changes visible to current JuMP users on Julia 0.6? We should be careful not to break existing setups.

**Comment by joaquimg** [comment]
It passes all the current JuMP (and MathProgBase) tests on 0.5 and 0.6 smoothly. The only change is that the user needs to use Xpress.XpressSolver instead of XpressSolver, which is not exported anymore.

**Comment by mlubin** [comment]
@joaquimg, could you make sure all solver tables are updated for un-exported name?

**Comment by odow** [comment]
Yes to CPLEX

**Comment by joaquimg** [comment]
GurobiMathOptInterface is passing almost all linear and integer tests - just needs status and ranged constraints.
I will submit a PR to Gurobi.jl due to some extra useful functions I needed.

Since Gurobi.jl exports `GurobiSolver` I needed to define `MOIGurobiSolver`, I would like suggestions in this point since Gurobi.jl e more beyond my control than Xpress.jl. I vote for stopping exporting `GurobiSolver`.

Opinions?

**Comment by mlubin** [comment]
We can't release a 0.6-compatible version of Gurobi.jl without `GurobiSolver` supported, it's too breaking. At that point, if we're going to declare Gurobi.jl `master` to be 0.7 only, might as well completely remove the MPB code.

**Comment by joaquimg** [comment]
Now we have [GurobiMathOptInterface.jl](https://github.com/JuliaOpt/GurobiMathOptInterface.jl) in JuliaOpt. It should be working as soon as https://github.com/JuliaOpt/Gurobi.jl/pull/106 gets merged and we tag a new version. Currently we have `MOIGurobiSolver` but in 0.7 we can stop exporting `GurobiSolver` in Gurobi.jl.

It passes most tests, does not passes ranged constraints because gurobi creates extra variables and some QCP tests fails due to problems with quadratic duals, which are not well posed in MOI anyway.

**Comment by joaquimg** [comment]
[MathOptInterfaceCPLEX](https://github.com/JuliaOpt/MathOptInterfaceCPLEX.jl) is passing all tests, but it needs: https://github.com/JuliaOpt/CPLEX.jl/pull/146.
There might be some work on that PR.

**Comment by joaquimg** [comment]
@IssamT any news on Clp? Have you considered using [LinQuadOptInterface](https://github.com/JuliaOpt/LinQuadOptInterface.jl)?

**Comment by IssamT** [comment]
@joaquimg, sorry for not replying quickly to your message. For some reason I stopped getting emails on comments of issues and pull requests despite I don't remember modifying my notification settings. I have enabled all the notifications on my settings and I hope this will fix it. 

About your question. I was a bit busy and only got some advance in the past week. Still a couple of tests and all will be passing. However It seems I also missed  LinQuadOptInterface. I wasn't aware of its existence. So no, I haven't used it.

**Comment by joaquimg** [comment]
MathOptInterfaceGLPK is alive: https://github.com/JuliaOpt/MathOptInterfaceGLPK.jl

It is passing most tests (the ones in MOI), there is still some important work to do: improving solution status mappings.

**Comment by blegat** [comment]
I will take care of updating CDD. Still no one working on MathOptInterfaceSCS.jl ?

**Comment by blegat** [comment]
I will start the SCS wrapper then :)

**Comment by joaquimg** [comment]
How can we proceed with CBC and SCIP?

I noticed SCIP's MPB interface is pretty simple, porting that to LQOI would be easy - once I have SCIP installed ;) - I just don't know if there is plan to do something special.

Should we extend CBC the same as CLP?
@IssamT have you put thoughts into that?

**Comment by mlubin** [comment]
CC @leethargo and @fserra for SCIP. There was talk at some point of writing a direct SCIP wrapper instead of using CSIP (which was written to provide a Gurobi-like C interface for SCIP). It would be easier to continue to use CSIP for now, but that may not be the long-term solution.

**Comment by leethargo** [comment]
True, a direct wrapper of the SCIP C-API would be more general. But I won't have time to attempt a rewrite in the next couple of months...

**Comment by blegat** [comment]
SCS is passing all the tests it can pass without bridge ! :)

**Comment by IssamT** [comment]
@joaquimg it would be nice to have CBC in the same style as CLP , but I haven't tried to use LQOI yet.

**Comment by blegat** [comment]
I can take care of ECOS, the interface is very similar to SCS so it should be quick :)

**Comment by blegat** [comment]
ECOS is now working :)

**Comment by odow** [comment]
Closing as I believe this issue has served its purpose.

**Comment by blegat** [comment]
CDD is done in https://github.com/JuliaPolyhedra/CDDLib.jl/pull/37
