### ISSUE TITLE
Unbounded test for linear continuous

### ISSUE THREAD

**Issue by matbesancon** [JuliaOpt/MathOptInterface.jl#708]
See https://github.com/JuliaOpt/Clp.jl/pull/60
The unbounded case seems untested, at least for linear problems

**Comment by blegat** [comment]
I agree, we should also add a constant in the objective and check that it is ignored in ObjectiveValue for the infeasibility ray (see https://github.com/JuliaOpt/MathOptInterface.jl/issues/433)

**Comment by matbesancon** [comment]
A non-tested example was added in JuliaOpt/Clp.jl#60
