### ISSUE TITLE
REDUCTION_CERTIFICATE

### ISSUE THREAD

**Issue by blegat** [JuliaOpt/MathOptInterface.jl#725]
We removed it as we thought it was dropped from Mosek (see https://github.com/JuliaOpt/MathOptInterface.jl/pull/575#discussion_r234392774) but I often still get it (with Mosek v8), i.e. these lines are executed:
https://github.com/JuliaOpt/MosekTools.jl/blob/d274a8381b6548f5ef25ad249e28884a6a557fed/src/attributes.jl#L494
https://github.com/JuliaOpt/MosekTools.jl/blob/d274a8381b6548f5ef25ad249e28884a6a557fed/src/attributes.jl#L519
and I get an `Undefined` error since it was removed from MOI.

@ulfworsoe @erling-d-andersen Was this feature removed in Mosek v9 ?

**Comment by erling-d-andersen** [comment]
I am not sure who did

  elseif solsta == MSK_SOL_STA_PRIM_ILLPOSED_CER
        MOI.NO_SOLUTION
    elseif solsta == MSK_SOL_STA_DUAL_ILLPOSED_CER
        MOI.REDUCTION_CERTIFICATE

Why do say no solution in one case and certificate in the other. To me it makes zero sense.

Both solution statuses are of course still possible. 

It v9 removed all the statuses that something with NEAR in them.

**Comment by blegat** [comment]
> Why do say no solution in one case and certificate in the other

For `MSK_SOL_STA_PRIM_ILLPOSED_CER`, the `MOI.PrimalStatus` is `MOI.NO_SOLUTION` and the `MOI.DualStatus` is `MOI.REDUCTION_CERTIFICATE` because the certificate is contained in the dual solution and there is no primal solution. This is similar to `MSK_SOL_STA_PRIM_INFEAS_CER` where there is no primal solution and the dual contains an infeasibility ray.

**Comment by erling-d-andersen** [comment]
Got it logic now.

**Comment by erling-d-andersen** [comment]
Btw if you see ill posed then you most likely have nasty model. Not that I cannot exclude a bug, but I would be worried about seeing illposed.

**Comment by blegat** [comment]
> Btw if you see ill posed then you most likely have nasty model.

Indeed, it is nasty by design. This is a model parametrized by some parameter `γ`. For `γ < γ*`, it is infeasible and for `γ > γ*`, it is feasible. I am doing bisection to find `γ*`.
https://github.com/blegat/SwitchOnSafety.jl/blob/a0b3e6de04e477a44e70bdb374d987620f8a736c/src/sos.jl#L217-L294
For some interval around `γ*`, the problem is ill conditioned and the solver fails to determine whether the problem is feasible or not.

**Comment by erling-d-andersen** [comment]
It is a hard one.
