### ISSUE TITLE
Update solvers to MOI v0.9

### ISSUE THREAD

**Issue by blegat** [JuliaOpt/MathOptInterface.jl#736]
Updates to do:

- Remove `MOI.SingleVariable` from the arguments of the `@model` macro.
- Implement `MOI.DualObjectiveValue`.
- Indices of `MOI.SingleVariable` constraints need to have the same index that the variable
- Implement `MOI.Silent`, `MOI.SolveTime`, `MOI.RawStatusString`, `MOI.TimeLimitSec`.
- Update the test script to follow the new guideline: http://www.juliaopt.org/MathOptInterface.jl/dev/apimanual/#Testing-guideline-1
- Add support for `MOI.RawParameter`.
- Rename `MOIU.getconstant` and `MOI._constant` to `MOI.constant`.
- Rename access to the `resultindex` field of `MOI.ObjectiveValue` to `result_index`.

For more details on what changed, see https://github.com/JuliaOpt/MathOptInterface.jl/pull/737

List of solvers is taken from http://www.juliaopt.org/JuMP.jl/dev/installation/#Getting-Solvers-1:

- [x] [KNITRO.jl](https://github.com/JuliaOpt/KNITRO.jl)
- [x] [Cbc.jl](https://github.com/JuliaOpt/Cbc.jl) https://github.com/JuliaOpt/Cbc.jl/pull/123
- [x] [CDCS.jl](https://github.com/blegat/CDCS.jl) https://github.com/blegat/CDCS.jl/pull/1
- [x] [Clp.jl](https://github.com/JuliaOpt/Clp.jl) https://github.com/JuliaOpt/Clp.jl/pull/66
- [x] [COSMO.jl](https://github.com/oxfordcontrol/COSMO.jl)
- [x] [CPLEX.jl](https://github.com/JuliaOpt/CPLEX.jl)  https://github.com/JuliaOpt/CPLEX.jl/pull/261
- [x] [CSDP.jl](https://github.com/JuliaOpt/CSDP.jl) https://github.com/JuliaOpt/CSDP.jl/pull/41
- [x] [ECOS.jl](https://github.com/JuliaOpt/ECOS.jl) https://github.com/JuliaOpt/ECOS.jl/pull/92
- [x] [Xpress.jl](https://github.com/JuliaOpt/Xpress.jl) https://github.com/JuliaOpt/Xpress.jl/pull/41
- [x] [GLPK.jl](https://github.com/JuliaOpt/GLPK.jl) https://github.com/JuliaOpt/GLPK.jl/pull/101
- [x] [Gurobi.jl](https://github.com/JuliaOpt/Gurobi.jl) https://github.com/JuliaOpt/Gurobi.jl/pull/216
- [X] [Ipopt.jl](https://github.com/JuliaOpt/Ipopt.jl) https://github.com/JuliaOpt/Ipopt.jl/pull/170
- [x] [Juniper.jl](https://github.com/lanl-ansi/Juniper.jl)
- [x] [MosekTools.jl](https://github.com/JuliaOpt/MosekTools.jl) https://github.com/JuliaOpt/MosekTools.jl/pull/38
- [x] [OSQP.jl](https://github.com/oxfordcontrol/OSQP.jl) https://github.com/oxfordcontrol/OSQP.jl/pull/55
- [x] [ProxSDP.jl](https://github.com/mariohsouto/ProxSDP.jl) https://github.com/mariohsouto/ProxSDP.jl/pull/58
- [x] [SCIP.jl](https://github.com/SCIP-Interfaces/SCIP.jl) https://github.com/SCIP-Interfaces/SCIP.jl/pull/126
- [x] [SCS.jl](https://github.com/JuliaOpt/SCS.jl) https://github.com/JuliaOpt/SCS.jl/pull/144
- [x] [SDPA.jl](https://github.com/JuliaOpt/SDPA.jl) https://github.com/JuliaOpt/SDPA.jl/pull/15
- [x] [SeDuMi.jl](https://github.com/JuliaOpt/SeDuMi.jl) https://github.com/JuliaOpt/SeDuMi.jl/pull/12

**Comment by rschwarz** [comment]
I think it would be good to merge #712 first. Right now, most MIP solvers will fail the Indicator tests, because the bridge is missing.

In SCIP, we have an implementation in a PR, but I think it would be cleaner to upgrade to MOI 0.9 first, then support Indicator constraints natively.

**Comment by mlubin** [comment]
GLPK, Ipopt, and SCS are the absolute minimum set of solvers needed to be ready before we tag MOI 0.9 so that we can run JuMP's examples under MOI 0.9.

**Comment by Wikunia** [comment]
Juniper now supports MOI 0.9 as well (since  v0.5.0)

**Comment by thanosdpapaioannou** [comment]
Hi, what is the status of DSDP.jl being updated to MOI v0.9? It appears [here](https://github.com/joehuchette/DSDP.jl/blob/bff9d1da8add7886fb727d65a1593f504b897bbd/REQUIRE#L3) that DSDP.jl only supports MOI version [0.8, 0.9).

**Comment by blegat** [comment]
I have a PR open: https://github.com/joehuchette/DSDP.jl/pull/10

**Comment by joaquimg** [comment]
Should we close this? since the list is complete?
