### ISSUE TITLE
Add default instantiation of a Model

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/MathOptInterface.jl#766]
See discussion at https://github.com/JuliaOpt/MathOptInterface.jl/pull/762#discussion_r291839757.

Motivation:
"I feel I'm casting spells rather than writing code at the moment" (https://github.com/JuliaOpt/SCS.jl/issues/145#issuecomment-500157689)

**Comment by blegat** [comment]
A good example is given in https://github.com/JuliaOpt/MathOptInterface.jl/blob/master/test/model.jl
