### ISSUE TITLE
move test/function_utilities.jl into src or MathOptInterfaceUtilities

### ISSUE THREAD

**Issue by chriscoey** [JuliaOpt/MathOptInterface.jl#79]
https://github.com/JuliaOpt/MathOptInterface.jl/blob/master/test/function_utilities.jl

is there anything else we want to redefine `Base.isapprox` for? may want to rename the file.

any preference where it goes?

**Comment by blegat** [comment]
It is already in MOIU: https://github.com/JuliaOpt/MathOptInterfaceUtilities.jl/blob/f82dc2a0746efc20621db35118acde5fad395ef1/src/functions.jl#L28-L72

**Comment by chriscoey** [comment]
is it OK to use MOIU and remove the file from test?

**Comment by blegat** [comment]
That is also what I would expect to happen

**Comment by mlubin** [comment]
Fine with me
