### ISSUE TITLE
need way to query what constraints can be added together

### ISSUE THREAD

**Issue by chriscoey** [JuliaOpt/MathOptInterface.jl#8]
from discussion with @mlubin, and following the fix to #6. 

define an interface for asking a solver 
- whether a group of "types" of constraints is supported together (ie a valid instance can be constructed with all of them)
- whether, given an existing instance that has already been solved, what types of constraints can be added to it

**Comment by chriscoey** [comment]
@mlubin looks like you've started to fix the first of these two

**Comment by mlubin** [comment]
Yep, first point is addressed by ``supportsproblem``.

**Comment by joaquimg** [comment]
> whether, given an existing instance that has already been solved, what types of constraints can be added to it

Is there any solver that works like this ?

If yes, what do you think about `canaddconstraint`? with the same arguments of `addconstraint`

**Comment by odow** [comment]
This can probably be closed now that there is `canaddconstraint` (ref https://github.com/JuliaOpt/MathOptInterface.jl/pull/129)
