### ISSUE TITLE
ObjectiveSense or OptimizationSense

### ISSUE THREAD

**Issue by remi-garcia** [JuliaOpt/MathOptInterface.jl#814]
https://github.com/JuliaOpt/MathOptInterface.jl/blob/0923d1e3a5fc9fdabc9c322bee84f29abe3805c3/src/attributes.jl#L473-L481
I think there is an inconsistency in the comment.
If I understand that well in the doc only `ObjectiveSense()` should appear, `OptimizationSense` is only here so that works on MOI side and MOI users don't need it. Is that right?
I also have noticed that `FeasiblitySense` should be `FEASIBILITY_SENSE`

Sorry if posting an issue wasn't what I should have done. I've still a lot to learn with MOI.

**Comment by mlubin** [comment]
`OptimizationSense` is the name of the enum, and `ObjectiveSense` is the name of the model attribute.

I agree the docstring is a bit confusing and should be reworded. It is meant to say that the the value of the `ObjectiveSense` must be an `OptimizationSense`, and the three options are `MIN_SENSE`, `MAX_SENSE`, or `FEASIBILITY_SENSE.` PR welcome :)
