### ISSUE TITLE
Check if constraints can be modified

### ISSUE THREAD

**Issue by joaquimg** [JuliaOpt/MathOptInterface.jl#85]

**Comment by mlubin** [comment]
Maybe `canmodifyconstraint` with the same signature as `modifyconstraint!`.

**Comment by joaquimg** [comment]
Should it be an attribute of the `Solver`?
Some solvers won´t allow modifying coefficients at all: `SupportsModifyConstraintCoefficients` but `SupportsModifyConstraintConstant` should be more common

**Comment by mlubin** [comment]
There are a lot of possible combinations of modifications to enumerate. If you're not precise enough the attributes don't help because a solver might support modifying the constant in a linear constraint but not in a SOC constraint.

**Comment by blegat** [comment]
Why not
```julia
supportmodifyconstraint(::AbstractSolverInstance, change::Type{<:Union{AbstractSet, AbstractFunction, AbstractFunctionModification}}, Type{<:AbstractFunction}, Type{<:AbstractSet})
```
