### ISSUE TITLE
MOI: Modeler-Optimizer Interface

### ISSUE THREAD

**Issue by odow** [JuliaOpt/MathOptInterface.jl#86]
Came across another use of MOI in a related context...

Bjarni V. Halldórsson , Erlendur S. Thorsteinsson , and Bjarni Kristjánsson (2000). A Modeling Interface to Non-Linear Programming Solvers - An instance: xMPS, the extended MPS format

http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.42.9202

**Comment by mlubin** [comment]
The few references I can find to that work seem to use the name xMPS, not MOI, so this doesn't seem too problematic.
