### ISSUE TITLE
Optimizer printing is too verbose

### ISSUE THREAD

**Issue by ericphanson** [JuliaOpt/MathOptInterface.jl#862]
Sorry if this has already been discussed somewhere; I didn't see an issue. If I accidentally let some optimizer object print to the REPL (maybe with nested layers of caches and bridges), it prints a huge amount. E.g. running
```julia
using SDPA_GMP, Convex, Test
E12, E21 = ComplexVariable(2, 2), ComplexVariable(2, 2)
s1, s2 = [big"0.25" big"-0.25"*im; big"0.25"*im big"0.25"], Complex{BigFloat}[big"0.5" big"0.0"; big"0.0" big"0.0"]
p = Problem{BigFloat}(:minimize, real(tr(E12 * (s1 + 2 * s2) + E21 * (s2 + 2 * s1))), [E12 ⪰ 0, E21 ⪰ 0, E12 + E21 == Diagonal(ones(2)) ])
solve!(p, SDPA_GMP.Optimizer())
p.MOI_model
```
means that last line yields 162_723 characters dumped in the REPL (as measured by `show`ing to a buffer, converting to a string, and asking for the `length`). (That code requires `https://github.com/ericphanson/Convex.jl#MathOptInterface` and `https://github.com/ericphanson/SDPA_GMP.jl`). 

Could MOI overload `show` to provide some kind of nice output? Maybe we could even somehow print a nice description of the various layers. Or even just redirect to `Base.summary` which gives e.g.
```julia
julia> summary(p.MOI_model)
"MathOptInterface.Utilities.CachingOptimizer{MathOptInterface.AbstractOptimizer,MathOptInterface.Utilities.Model{BigFloat}}"
```
That doesn't seem too bad, and seems way more helpful than a massive wall of text.

**Comment by odow** [comment]
Any PR to improve printing would be great! Printing the summary seems helpful.

In the solvers, I have overloaded `show` (e.g., [Gurobi](https://github.com/JuliaOpt/Gurobi.jl/blob/db91e1e9fabc3f62f30265780e6a577016ebba4e/src/MOI_wrapper.jl#L139)), but this doesn't work when Gurobi get's wrapped in a bridge.

**Comment by ericphanson** [comment]
Ok great, glad you're open to it! I'll try a few things locally and post a PR (probably soon, but possibly not).

**Comment by blegat** [comment]
This also annoyed me several times, showing `summary` by default seems reasonable.
