### ISSUE TITLE
Add MOI tests for DualExponentialCone and DualPowerCone Problems

### ISSUE THREAD

**Issue by guilhermebodin** [JuliaOpt/MathOptInterface.jl#868]
This would help to tests the cone support for SCS and COSMO, maybe others too.

**Comment by guilhermebodin** [comment]
https://github.com/JuliaOpt/SCS.jl/pull/154

**Comment by blegat** [comment]
@guilhermebodin Is it resolved by https://github.com/JuliaOpt/MathOptInterface.jl/pull/873 ?

**Comment by guilhermebodin** [comment]
Yes :)
