### ISSUE TITLE
Allocate load problem with constrained variables

### ISSUE THREAD

**Issue by joaquimg** [JuliaOpt/MathOptInterface.jl#875]
I am trying to update https://github.com/mariohsouto/ProxSDP.jl/pull/57 to MOI v0.9.z.

However the following test fails:
```julia
    MOI.empty!(optimizer)

    x = MOI.add_variable(optimizer)
    X = [x, x, x]

    vov = MOI.VectorOfVariables(X)
    cX = MOI.add_constraint(optimizer, vov, MOI.PositiveSemidefiniteConeTriangle(2))

    c = MOI.add_constraint(optimizer, MOI.ScalarAffineFunction([MOI.ScalarAffineTerm(1.0, X[2])], 0.0), MOI.EqualTo(1.0))

    MOI.set(optimizer, MOI.ObjectiveFunction{MOI.ScalarAffineFunction{Float64}}(), MOI.ScalarAffineFunction(MOI.ScalarAffineTerm.(1.0, [X[1], X[3]]), 0.0))

    MOI.set(optimizer, MOI.ObjectiveSense(), MOI.MIN_SENSE)
    MOI.optimize!(optimizer)
```

this is due to this fallback:
```julia
"""
    allocate_constrained_variables(model::MOI.ModelLike,
                                   set::MOI.AbstractVectorSet)

Returns a tuple with the variable indices and the index for the constraint to be
used in `load_allocate_constraint`.
"""
function allocate_constrained_variables(model::MOI.ModelLike,
                                        set::MOI.AbstractVectorSet)
    variables = allocate_variables(model, MOI.dimension(set))
    func = MOI.VectorOfVariables(variables)
    constraint = allocate_constraint(model, func, set)
    return variables, constraint
end
```

which is assuming that there are no duplicates in VOV.

We probably need , docs at least, I will try to go into allocate-load API carefully.

**Comment by joaquimg** [comment]
Also, What if one variable appears in two VOV's?

**Comment by joaquimg** [comment]
by passing the function to ` MOIU.allocate_constrained_variables` I could fix the issue in ProxSDP.
I only create variables for the unique variables in the function.

**Comment by joaquimg** [comment]
the fix is trivial, just one line in the function:
```julia
function MOIU.allocate_vector_of_variables(dest::Optimizer, src::MOI.ModelLike,
    idxmap::MOIU.IndexMap,
    S::Type{<:MOI.AbstractSet})
    allocated = MOI.ConstraintIndex{MOI.VectorOfVariables, S}[]
    not_allocated = MOI.ConstraintIndex{MOI.VectorOfVariables, S}[]
    cis_src = MOI.get(src, MOI.ListOfConstraintIndices{MOI.VectorOfVariables, S}())
    fs_src = MOI.get(src, MOI.ConstraintFunction(), cis_src)::Vector{MOI.VectorOfVariables}
    for (ci_src, f_src) in zip(cis_src, fs_src)
        if all(vi -> !haskey(idxmap, vi), f_src.variables)
            set = MOI.get(src, MOI.ConstraintSet(), ci_src)::S
            # this is the moficiation v
            # vis_dest, ci_dest = allocate_constrained_variables(dest, set)
            vis_dest, ci_dest = MOIU.allocate_constrained_variables(dest, f_src, set)
            idxmap[ci_src] = ci_dest
            for (vi_src, vi_dest) in zip(f_src.variables, vis_dest)
                idxmap[vi_src] = vi_dest
            end
            push!(allocated, ci_src)
        else
            push!(not_allocated, ci_src)
        end
    end
    return allocated, not_allocated
end
```
Temporarily implemented in: https://github.com/mariohsouto/ProxSDP.jl/pull/58

**Comment by blegat** [comment]
> which is assuming that there are no duplicates in VOV.

This is ensured by
https://github.com/JuliaOpt/MathOptInterface.jl/blob/98a0e472e1757db14b849bbba8fe84597856def2/src/Utilities/copy.jl#L171
so I don't understand what is the issue.
Moreover, `add_constrained_variables` also create new variables, just like `allocate_constrained_variables` so this is not related to the Allocate-Load API.
The fix seems incorrect because `f_src` is in the index-space of `src` so it cannot be given to `dest`.

**Comment by joaquimg** [comment]
What I mean by "no duplicates in VOV" is assuring the same variable does not appears twice in the same VOV.

The line ensuring that, is this: `if all(vi -> !haskey(idxmap, vi), f_src.variables)` right?
From what I could understand this check if the variable was previously added, due to another VOV-in-set constraint.

Yes, I know that `f_src` lives in a different index-space, but I need it to check how many of its variable were duplicates. Otherwise the number of variables added is always equal to the size of the vector set and no the actual number of unique variables in that set.

**Comment by blegat** [comment]
Indeed, if the same variables is twice in the vector then the check is not sufficient. We should also add a check that no variables appear twice in that `if`

**Comment by joaquimg** [comment]
Then we can just add a `allunique(f_src.variables)`

**Comment by blegat** [comment]
Yes, that would be the way to go
