### ISSUE TITLE
Change constraint "sense"

### ISSUE THREAD

**Issue by joaquimg** [JuliaOpt/MathOptInterface.jl#89]
Many solvers allow us to change the constraint from equality to inequality. The first idea was not to support it https://github.com/JuliaOpt/MathOptInterface.jl/pull/38/commits/f245a6ac10a18da2463c612c7859017e00e76414 , one had to delete a constraint and add a new one, however some solver might be able to modify the sign and not be able to delete. Moreover modifying looks simpler.

The idea is to have something along the lines:
```julia
c_new = modifyconstraint(m::SolverInstance, ::MOI.ConstraintSet, 
    c::MOI.ConstraintReference{F, MOI.LessThan{T}}, 
    newset::MOI.EquaTo{T})::MOI.ConstraintReference{F, MOI.EqualTo{T}}
```

**Comment by mlubin** [comment]
I think we should have separate names for methods that modify constraints without invalidating the constraint reference and those which modify constraints and return a new reference. Maybe ``transformconstraint!`` instead of ``modifyconstraint!``?

**Comment by joaquimg** [comment]
It could `transformconstraint!` to make it very clear it does something a bit different.

**Comment by blegat** [comment]
I would remove the `MOI.ConstraintSet` argument in order to be consistent with `modifyconstraint!` ?
