### ISSUE TITLE
UndefVarError: UnsetSolver not defined

### ISSUE THREAD

**Issue by parshinshojaee** [JuliaOpt/MathOptInterface.jl#919]
Hey,
I already installed GLPKMathProgInterface package, but whenever I use
m=model (solver=GLPKSolverLP())
I get this error: UndefVarError: UnsetSolver not defined

Does anybody know that solving syntaxes have changed from Julia 1.1.1 to 1.2.0??

**Comment by odow** [comment]
You should upgrade to JuMP 0.20 (i.e., run `] up`). In addition, `GLPKMathProgInterface` has been replaced by the `GLPK` package. 

So you want:
```Julia
using GLPK
model = Model(with_optimizer(GLPK.Optimizer))
```

Note that a considerable amount of JuMP syntax has changed. You should read the documentation to familiarize yourself: https://www.juliaopt.org/JuMP.jl/v0.20.0/quickstart/

If you run into any trouble, you can search the forum for answers: https://discourse.julialang.org/c/domain/opt. If you are still stuck, feel free to open a new post on the forum.
