### ISSUE TITLE
More info about TerminationStatus/PrimalStatus etc

### ISSUE THREAD

**Issue by joaquimg** [JuliaOpt/MathOptInterface.jl#99]
Should we have a minimally standardized way to return more info about the status?

Some output info of [Xpress and CPLEX](https://github.com/JuliaOpt/Xpress.jl/pull/10#discussion_r130509494) do not match any existing status (and probably should not match at all) but we could have a default way to return a string/symbol/error/warning with that extra info.

**Comment by blegat** [comment]
Having an attribute that returns a string would be nice indeed.

**Comment by mlubin** [comment]
``SpecificTerminationStatus`` (or another name) is fine as an attribute where solvers could return a solver-dependent string. Could we discuss the specific cases that don't map well? We put a lot of work into designing the status codes...

**Comment by odow** [comment]
I think the statuses are great. It's more a case of how much effort we should put in.

CPLEX solves an LP, returns `CPX_STAT_INForUNBD`. It also returns `CPX_NO_SOLN` so I don't have any information on the primal or dual. Should I stop there or try to find a certificate? https://github.com/JuliaOpt/CPLEX.jl/pull/139/files#diff-5b9fa9efaaa021b1607ca6ccdfc75248R40 

And if I do, is the termination status now `Success`? Because what about the time limit?

**Comment by mlubin** [comment]
``CPX_STAT_INForUNBD`` maps directly to ``InfeasibleOrUnbounded`` and I presume no solution is available so there is no primal status code to return.

``CPX_NO_SOLN`` is seems like a solution status, not a termination status. If there is no solution available you should simply say that ``cangetattribute(...,PrimalStatus()) == false``.

**Comment by odow** [comment]
Should there be a resultstatuscode for `NoResult`?

**Comment by mlubin** [comment]
No, primal status is tied to a result number (http://www.juliaopt.org/MathOptInterface.jl/latest/apireference.html#MathOptInterface.PrimalStatus). If no number is provided, it defaults to 1. If there are zero results, then the primal status of result number 1 simply cannot be accessed.

**Comment by odow** [comment]
Ah I missed this. I'll add some tests

**Comment by odow** [comment]
Should there be a `PrimalResultCount` and `DualResultCount`?

**Comment by joaquimg** [comment]
Makes sense for me

**Comment by mlubin** [comment]
The original concept was to have a single result count since I'd consider the primal-dual pair to be tied together. If either the primal or dual part of a result is missing, then that information is available though ``cangetattribute``.

**Comment by IssamT** [comment]
@mlubin, could you please clarify you last message? Should `ResultCount` be 1 or 0 when the problem is dual feasible but not primal feasible.

**Comment by mlubin** [comment]
@IssamT, it should be 1. If the solver is in the middle of running and has a dual feasible vector (`DualStatus(1)` is `FeasiblePoint`) and a primal vector is available but is known to be infeasible, `PrimalStatus(1)` can return `InfeasiblePoint` and make the values available via `VariablePrimal(1)`.

If we're talking about a dual vector serving as a certificate of primal infeasibility, then `DualStatus(1)` should be `InfeasibilityCertificate` and `PrimalStatus(1)` should be unavailable.

**Comment by IssamT** [comment]
Clear. Thanks.
